// This file is auto-generated by the autobind tool. Do not edit manually.
#pragma once
#include <quickjs.h>
#include <memory>

namespace RaylibBindings {

    // Class IDs for struct bindings
    inline JSClassID js_Vector2_class_id;
    inline JSClassID js_Vector3_class_id;
    inline JSClassID js_Vector4_class_id;
    inline JSClassID js_Matrix_class_id;
    inline JSClassID js_Color_class_id;
    inline JSClassID js_Rectangle_class_id;
    inline JSClassID js_Image_class_id;
    inline JSClassID js_Texture_class_id;

    // Alias IDs for struct bindings
    inline JSClassID js_Texture2D_class_id;

    JSValue JS_NewVector2(JSContext *ctx, Vector2 data);
    JSValue JS_NewVector3(JSContext *ctx, Vector3 data);
    JSValue JS_NewVector4(JSContext *ctx, Vector4 data);
    JSValue JS_NewMatrix(JSContext *ctx, Matrix data);
    JSValue JS_NewColor(JSContext *ctx, Color data);
    JSValue JS_NewRectangle(JSContext *ctx, Rectangle data);
    JSValue JS_NewImage(JSContext *ctx, Image data);
    JSValue JS_NewTexture(JSContext *ctx, Texture data);

    JSValue JS_NewTexture2D(JSContext *ctx, Texture data);

    void InitAllStructs(JSContext *ctx, JSValue ns);

    JSValue JS_IsWindowReady(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_IsWindowFullscreen(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_IsWindowHidden(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_IsWindowMinimized(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_IsWindowMaximized(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_IsWindowFocused(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_IsWindowResized(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_IsWindowState(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_SetWindowState(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_ClearWindowState(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_GetScreenWidth(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_GetScreenHeight(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_GetRenderWidth(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_GetRenderHeight(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_GetMonitorCount(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_GetMonitorWidth(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_GetMonitorHeight(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_GetMonitorPhysicalWidth(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_GetMonitorPhysicalHeight(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_GetMonitorRefreshRate(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_GetWindowPosition(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_GetWindowScaleDPI(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_IsKeyPressed(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_IsKeyPressedRepeat(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_IsKeyDown(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_IsKeyReleased(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_IsKeyUp(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_GetKeyPressed(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_SetExitKey(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_IsMouseButtonPressed(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_IsMouseButtonDown(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_IsMouseButtonReleased(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_IsMouseButtonUp(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_GetMouseX(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_GetMouseY(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_GetMousePosition(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_SetMousePosition(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_SetMouseOffset(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_SetMouseScale(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_GetMouseWheelMove(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_GetMouseWheelMoveV(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_DrawPixel(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_DrawLine(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_DrawCircle(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_DrawRectangle(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_LoadTexture(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_UnloadTexture(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_DrawTexture(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_DrawFPS(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;
    JSValue JS_DrawText(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept;

    void InitAllFunctions(JSContext *ctx, JSValue ns);
    void InitAllEnums(JSContext *ctx, JSValue global_obj);

}