// This file is auto-generated by the autobind tool. Do not edit manually.

#include <quickjs.h>

namespace RaylibBindings {

    void InitAllEnums(JSContext *ctx, JSValue global_obj) {

        // Enum: ConfigFlags
        const JSValue ConfigFlags_ns = JS_NewObject(ctx);
        JS_SetPropertyStr(ctx, global_obj, "ConfigFlags", ConfigFlags_ns);
        JS_SetPropertyStr(ctx, ConfigFlags_ns, "FLAG_VSYNC_HINT", JS_NewInt32(ctx, 64));
        JS_SetPropertyStr(ctx, ConfigFlags_ns, "FLAG_FULLSCREEN_MODE", JS_NewInt32(ctx, 2));
        JS_SetPropertyStr(ctx, ConfigFlags_ns, "FLAG_WINDOW_RESIZABLE", JS_NewInt32(ctx, 4));
        JS_SetPropertyStr(ctx, ConfigFlags_ns, "FLAG_WINDOW_UNDECORATED", JS_NewInt32(ctx, 8));
        JS_SetPropertyStr(ctx, ConfigFlags_ns, "FLAG_WINDOW_HIDDEN", JS_NewInt32(ctx, 128));
        JS_SetPropertyStr(ctx, ConfigFlags_ns, "FLAG_WINDOW_MINIMIZED", JS_NewInt32(ctx, 512));
        JS_SetPropertyStr(ctx, ConfigFlags_ns, "FLAG_WINDOW_MAXIMIZED", JS_NewInt32(ctx, 1024));
        JS_SetPropertyStr(ctx, ConfigFlags_ns, "FLAG_WINDOW_UNFOCUSED", JS_NewInt32(ctx, 2048));
        JS_SetPropertyStr(ctx, ConfigFlags_ns, "FLAG_WINDOW_TOPMOST", JS_NewInt32(ctx, 4096));
        JS_SetPropertyStr(ctx, ConfigFlags_ns, "FLAG_WINDOW_ALWAYS_RUN", JS_NewInt32(ctx, 256));
        JS_SetPropertyStr(ctx, ConfigFlags_ns, "FLAG_WINDOW_TRANSPARENT", JS_NewInt32(ctx, 16));
        JS_SetPropertyStr(ctx, ConfigFlags_ns, "FLAG_WINDOW_HIGHDPI", JS_NewInt32(ctx, 8192));
        JS_SetPropertyStr(ctx, ConfigFlags_ns, "FLAG_WINDOW_MOUSE_PASSTHROUGH", JS_NewInt32(ctx, 16384));
        JS_SetPropertyStr(ctx, ConfigFlags_ns, "FLAG_BORDERLESS_WINDOWED_MODE", JS_NewInt32(ctx, 32768));
        JS_SetPropertyStr(ctx, ConfigFlags_ns, "FLAG_MSAA_4X_HINT", JS_NewInt32(ctx, 32));
        JS_SetPropertyStr(ctx, ConfigFlags_ns, "FLAG_INTERLACED_HINT", JS_NewInt32(ctx, 65536));

        // Enum: TraceLogLevel
        const JSValue TraceLogLevel_ns = JS_NewObject(ctx);
        JS_SetPropertyStr(ctx, global_obj, "TraceLogLevel", TraceLogLevel_ns);
        JS_SetPropertyStr(ctx, TraceLogLevel_ns, "LOG_ALL", JS_NewInt32(ctx, 0));
        JS_SetPropertyStr(ctx, TraceLogLevel_ns, "LOG_TRACE", JS_NewInt32(ctx, 1));
        JS_SetPropertyStr(ctx, TraceLogLevel_ns, "LOG_DEBUG", JS_NewInt32(ctx, 2));
        JS_SetPropertyStr(ctx, TraceLogLevel_ns, "LOG_INFO", JS_NewInt32(ctx, 3));
        JS_SetPropertyStr(ctx, TraceLogLevel_ns, "LOG_WARNING", JS_NewInt32(ctx, 4));
        JS_SetPropertyStr(ctx, TraceLogLevel_ns, "LOG_ERROR", JS_NewInt32(ctx, 5));
        JS_SetPropertyStr(ctx, TraceLogLevel_ns, "LOG_FATAL", JS_NewInt32(ctx, 6));
        JS_SetPropertyStr(ctx, TraceLogLevel_ns, "LOG_NONE", JS_NewInt32(ctx, 7));

        // Enum: KeyboardKey
        const JSValue KeyboardKey_ns = JS_NewObject(ctx);
        JS_SetPropertyStr(ctx, global_obj, "KeyboardKey", KeyboardKey_ns);
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_NULL", JS_NewInt32(ctx, 0));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_APOSTROPHE", JS_NewInt32(ctx, 39));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_COMMA", JS_NewInt32(ctx, 44));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_MINUS", JS_NewInt32(ctx, 45));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_PERIOD", JS_NewInt32(ctx, 46));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_SLASH", JS_NewInt32(ctx, 47));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_ZERO", JS_NewInt32(ctx, 48));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_ONE", JS_NewInt32(ctx, 49));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_TWO", JS_NewInt32(ctx, 50));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_THREE", JS_NewInt32(ctx, 51));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_FOUR", JS_NewInt32(ctx, 52));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_FIVE", JS_NewInt32(ctx, 53));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_SIX", JS_NewInt32(ctx, 54));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_SEVEN", JS_NewInt32(ctx, 55));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_EIGHT", JS_NewInt32(ctx, 56));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_NINE", JS_NewInt32(ctx, 57));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_SEMICOLON", JS_NewInt32(ctx, 59));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_EQUAL", JS_NewInt32(ctx, 61));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_A", JS_NewInt32(ctx, 65));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_B", JS_NewInt32(ctx, 66));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_C", JS_NewInt32(ctx, 67));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_D", JS_NewInt32(ctx, 68));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_E", JS_NewInt32(ctx, 69));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_F", JS_NewInt32(ctx, 70));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_G", JS_NewInt32(ctx, 71));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_H", JS_NewInt32(ctx, 72));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_I", JS_NewInt32(ctx, 73));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_J", JS_NewInt32(ctx, 74));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_K", JS_NewInt32(ctx, 75));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_L", JS_NewInt32(ctx, 76));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_M", JS_NewInt32(ctx, 77));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_N", JS_NewInt32(ctx, 78));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_O", JS_NewInt32(ctx, 79));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_P", JS_NewInt32(ctx, 80));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_Q", JS_NewInt32(ctx, 81));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_R", JS_NewInt32(ctx, 82));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_S", JS_NewInt32(ctx, 83));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_T", JS_NewInt32(ctx, 84));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_U", JS_NewInt32(ctx, 85));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_V", JS_NewInt32(ctx, 86));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_W", JS_NewInt32(ctx, 87));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_X", JS_NewInt32(ctx, 88));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_Y", JS_NewInt32(ctx, 89));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_Z", JS_NewInt32(ctx, 90));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_LEFT_BRACKET", JS_NewInt32(ctx, 91));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_BACKSLASH", JS_NewInt32(ctx, 92));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_RIGHT_BRACKET", JS_NewInt32(ctx, 93));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_GRAVE", JS_NewInt32(ctx, 96));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_SPACE", JS_NewInt32(ctx, 32));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_ESCAPE", JS_NewInt32(ctx, 256));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_ENTER", JS_NewInt32(ctx, 257));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_TAB", JS_NewInt32(ctx, 258));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_BACKSPACE", JS_NewInt32(ctx, 259));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_INSERT", JS_NewInt32(ctx, 260));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_DELETE", JS_NewInt32(ctx, 261));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_RIGHT", JS_NewInt32(ctx, 262));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_LEFT", JS_NewInt32(ctx, 263));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_DOWN", JS_NewInt32(ctx, 264));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_UP", JS_NewInt32(ctx, 265));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_PAGE_UP", JS_NewInt32(ctx, 266));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_PAGE_DOWN", JS_NewInt32(ctx, 267));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_HOME", JS_NewInt32(ctx, 268));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_END", JS_NewInt32(ctx, 269));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_CAPS_LOCK", JS_NewInt32(ctx, 280));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_SCROLL_LOCK", JS_NewInt32(ctx, 281));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_NUM_LOCK", JS_NewInt32(ctx, 282));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_PRINT_SCREEN", JS_NewInt32(ctx, 283));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_PAUSE", JS_NewInt32(ctx, 284));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_F1", JS_NewInt32(ctx, 290));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_F2", JS_NewInt32(ctx, 291));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_F3", JS_NewInt32(ctx, 292));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_F4", JS_NewInt32(ctx, 293));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_F5", JS_NewInt32(ctx, 294));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_F6", JS_NewInt32(ctx, 295));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_F7", JS_NewInt32(ctx, 296));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_F8", JS_NewInt32(ctx, 297));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_F9", JS_NewInt32(ctx, 298));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_F10", JS_NewInt32(ctx, 299));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_F11", JS_NewInt32(ctx, 300));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_F12", JS_NewInt32(ctx, 301));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_LEFT_SHIFT", JS_NewInt32(ctx, 340));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_LEFT_CONTROL", JS_NewInt32(ctx, 341));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_LEFT_ALT", JS_NewInt32(ctx, 342));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_LEFT_SUPER", JS_NewInt32(ctx, 343));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_RIGHT_SHIFT", JS_NewInt32(ctx, 344));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_RIGHT_CONTROL", JS_NewInt32(ctx, 345));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_RIGHT_ALT", JS_NewInt32(ctx, 346));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_RIGHT_SUPER", JS_NewInt32(ctx, 347));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_KB_MENU", JS_NewInt32(ctx, 348));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_KP_0", JS_NewInt32(ctx, 320));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_KP_1", JS_NewInt32(ctx, 321));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_KP_2", JS_NewInt32(ctx, 322));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_KP_3", JS_NewInt32(ctx, 323));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_KP_4", JS_NewInt32(ctx, 324));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_KP_5", JS_NewInt32(ctx, 325));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_KP_6", JS_NewInt32(ctx, 326));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_KP_7", JS_NewInt32(ctx, 327));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_KP_8", JS_NewInt32(ctx, 328));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_KP_9", JS_NewInt32(ctx, 329));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_KP_DECIMAL", JS_NewInt32(ctx, 330));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_KP_DIVIDE", JS_NewInt32(ctx, 331));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_KP_MULTIPLY", JS_NewInt32(ctx, 332));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_KP_SUBTRACT", JS_NewInt32(ctx, 333));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_KP_ADD", JS_NewInt32(ctx, 334));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_KP_ENTER", JS_NewInt32(ctx, 335));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_KP_EQUAL", JS_NewInt32(ctx, 336));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_BACK", JS_NewInt32(ctx, 4));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_MENU", JS_NewInt32(ctx, 5));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_VOLUME_UP", JS_NewInt32(ctx, 24));
        JS_SetPropertyStr(ctx, KeyboardKey_ns, "KEY_VOLUME_DOWN", JS_NewInt32(ctx, 25));

        // Enum: MouseButton
        const JSValue MouseButton_ns = JS_NewObject(ctx);
        JS_SetPropertyStr(ctx, global_obj, "MouseButton", MouseButton_ns);
        JS_SetPropertyStr(ctx, MouseButton_ns, "MOUSE_BUTTON_LEFT", JS_NewInt32(ctx, 0));
        JS_SetPropertyStr(ctx, MouseButton_ns, "MOUSE_BUTTON_RIGHT", JS_NewInt32(ctx, 1));
        JS_SetPropertyStr(ctx, MouseButton_ns, "MOUSE_BUTTON_MIDDLE", JS_NewInt32(ctx, 2));
        JS_SetPropertyStr(ctx, MouseButton_ns, "MOUSE_BUTTON_SIDE", JS_NewInt32(ctx, 3));
        JS_SetPropertyStr(ctx, MouseButton_ns, "MOUSE_BUTTON_EXTRA", JS_NewInt32(ctx, 4));
        JS_SetPropertyStr(ctx, MouseButton_ns, "MOUSE_BUTTON_FORWARD", JS_NewInt32(ctx, 5));
        JS_SetPropertyStr(ctx, MouseButton_ns, "MOUSE_BUTTON_BACK", JS_NewInt32(ctx, 6));

        // Enum: MouseCursor
        const JSValue MouseCursor_ns = JS_NewObject(ctx);
        JS_SetPropertyStr(ctx, global_obj, "MouseCursor", MouseCursor_ns);
        JS_SetPropertyStr(ctx, MouseCursor_ns, "MOUSE_CURSOR_DEFAULT", JS_NewInt32(ctx, 0));
        JS_SetPropertyStr(ctx, MouseCursor_ns, "MOUSE_CURSOR_ARROW", JS_NewInt32(ctx, 1));
        JS_SetPropertyStr(ctx, MouseCursor_ns, "MOUSE_CURSOR_IBEAM", JS_NewInt32(ctx, 2));
        JS_SetPropertyStr(ctx, MouseCursor_ns, "MOUSE_CURSOR_CROSSHAIR", JS_NewInt32(ctx, 3));
        JS_SetPropertyStr(ctx, MouseCursor_ns, "MOUSE_CURSOR_POINTING_HAND", JS_NewInt32(ctx, 4));
        JS_SetPropertyStr(ctx, MouseCursor_ns, "MOUSE_CURSOR_RESIZE_EW", JS_NewInt32(ctx, 5));
        JS_SetPropertyStr(ctx, MouseCursor_ns, "MOUSE_CURSOR_RESIZE_NS", JS_NewInt32(ctx, 6));
        JS_SetPropertyStr(ctx, MouseCursor_ns, "MOUSE_CURSOR_RESIZE_NWSE", JS_NewInt32(ctx, 7));
        JS_SetPropertyStr(ctx, MouseCursor_ns, "MOUSE_CURSOR_RESIZE_NESW", JS_NewInt32(ctx, 8));
        JS_SetPropertyStr(ctx, MouseCursor_ns, "MOUSE_CURSOR_RESIZE_ALL", JS_NewInt32(ctx, 9));
        JS_SetPropertyStr(ctx, MouseCursor_ns, "MOUSE_CURSOR_NOT_ALLOWED", JS_NewInt32(ctx, 10));

        // Enum: GamepadButton
        const JSValue GamepadButton_ns = JS_NewObject(ctx);
        JS_SetPropertyStr(ctx, global_obj, "GamepadButton", GamepadButton_ns);
        JS_SetPropertyStr(ctx, GamepadButton_ns, "GAMEPAD_BUTTON_UNKNOWN", JS_NewInt32(ctx, 0));
        JS_SetPropertyStr(ctx, GamepadButton_ns, "GAMEPAD_BUTTON_LEFT_FACE_UP", JS_NewInt32(ctx, 1));
        JS_SetPropertyStr(ctx, GamepadButton_ns, "GAMEPAD_BUTTON_LEFT_FACE_RIGHT", JS_NewInt32(ctx, 2));
        JS_SetPropertyStr(ctx, GamepadButton_ns, "GAMEPAD_BUTTON_LEFT_FACE_DOWN", JS_NewInt32(ctx, 3));
        JS_SetPropertyStr(ctx, GamepadButton_ns, "GAMEPAD_BUTTON_LEFT_FACE_LEFT", JS_NewInt32(ctx, 4));
        JS_SetPropertyStr(ctx, GamepadButton_ns, "GAMEPAD_BUTTON_RIGHT_FACE_UP", JS_NewInt32(ctx, 5));
        JS_SetPropertyStr(ctx, GamepadButton_ns, "GAMEPAD_BUTTON_RIGHT_FACE_RIGHT", JS_NewInt32(ctx, 6));
        JS_SetPropertyStr(ctx, GamepadButton_ns, "GAMEPAD_BUTTON_RIGHT_FACE_DOWN", JS_NewInt32(ctx, 7));
        JS_SetPropertyStr(ctx, GamepadButton_ns, "GAMEPAD_BUTTON_RIGHT_FACE_LEFT", JS_NewInt32(ctx, 8));
        JS_SetPropertyStr(ctx, GamepadButton_ns, "GAMEPAD_BUTTON_LEFT_TRIGGER_1", JS_NewInt32(ctx, 9));
        JS_SetPropertyStr(ctx, GamepadButton_ns, "GAMEPAD_BUTTON_LEFT_TRIGGER_2", JS_NewInt32(ctx, 10));
        JS_SetPropertyStr(ctx, GamepadButton_ns, "GAMEPAD_BUTTON_RIGHT_TRIGGER_1", JS_NewInt32(ctx, 11));
        JS_SetPropertyStr(ctx, GamepadButton_ns, "GAMEPAD_BUTTON_RIGHT_TRIGGER_2", JS_NewInt32(ctx, 12));
        JS_SetPropertyStr(ctx, GamepadButton_ns, "GAMEPAD_BUTTON_MIDDLE_LEFT", JS_NewInt32(ctx, 13));
        JS_SetPropertyStr(ctx, GamepadButton_ns, "GAMEPAD_BUTTON_MIDDLE", JS_NewInt32(ctx, 14));
        JS_SetPropertyStr(ctx, GamepadButton_ns, "GAMEPAD_BUTTON_MIDDLE_RIGHT", JS_NewInt32(ctx, 15));
        JS_SetPropertyStr(ctx, GamepadButton_ns, "GAMEPAD_BUTTON_LEFT_THUMB", JS_NewInt32(ctx, 16));
        JS_SetPropertyStr(ctx, GamepadButton_ns, "GAMEPAD_BUTTON_RIGHT_THUMB", JS_NewInt32(ctx, 17));

        // Enum: GamepadAxis
        const JSValue GamepadAxis_ns = JS_NewObject(ctx);
        JS_SetPropertyStr(ctx, global_obj, "GamepadAxis", GamepadAxis_ns);
        JS_SetPropertyStr(ctx, GamepadAxis_ns, "GAMEPAD_AXIS_LEFT_X", JS_NewInt32(ctx, 0));
        JS_SetPropertyStr(ctx, GamepadAxis_ns, "GAMEPAD_AXIS_LEFT_Y", JS_NewInt32(ctx, 1));
        JS_SetPropertyStr(ctx, GamepadAxis_ns, "GAMEPAD_AXIS_RIGHT_X", JS_NewInt32(ctx, 2));
        JS_SetPropertyStr(ctx, GamepadAxis_ns, "GAMEPAD_AXIS_RIGHT_Y", JS_NewInt32(ctx, 3));
        JS_SetPropertyStr(ctx, GamepadAxis_ns, "GAMEPAD_AXIS_LEFT_TRIGGER", JS_NewInt32(ctx, 4));
        JS_SetPropertyStr(ctx, GamepadAxis_ns, "GAMEPAD_AXIS_RIGHT_TRIGGER", JS_NewInt32(ctx, 5));

        // Enum: CameraMode
        const JSValue CameraMode_ns = JS_NewObject(ctx);
        JS_SetPropertyStr(ctx, global_obj, "CameraMode", CameraMode_ns);
        JS_SetPropertyStr(ctx, CameraMode_ns, "CAMERA_CUSTOM", JS_NewInt32(ctx, 0));
        JS_SetPropertyStr(ctx, CameraMode_ns, "CAMERA_FREE", JS_NewInt32(ctx, 1));
        JS_SetPropertyStr(ctx, CameraMode_ns, "CAMERA_ORBITAL", JS_NewInt32(ctx, 2));
        JS_SetPropertyStr(ctx, CameraMode_ns, "CAMERA_FIRST_PERSON", JS_NewInt32(ctx, 3));
        JS_SetPropertyStr(ctx, CameraMode_ns, "CAMERA_THIRD_PERSON", JS_NewInt32(ctx, 4));

        // Enum: CameraProjection
        const JSValue CameraProjection_ns = JS_NewObject(ctx);
        JS_SetPropertyStr(ctx, global_obj, "CameraProjection", CameraProjection_ns);
        JS_SetPropertyStr(ctx, CameraProjection_ns, "CAMERA_PERSPECTIVE", JS_NewInt32(ctx, 0));
        JS_SetPropertyStr(ctx, CameraProjection_ns, "CAMERA_ORTHOGRAPHIC", JS_NewInt32(ctx, 1));

    }

}