// This file is auto-generated by the autobind tool. Do not edit manually.

#include <quickjs.h>
#include <raylib.h>
#include "rl_bindings.hpp"

namespace RaylibBindings {

    JSValue JS_NewVector2(JSContext *ctx, Vector2 data) {
        const JSValue obj = JS_NewObjectClass(ctx, js_Vector2_class_id);
        if (auto* s = static_cast<Vector2*>(js_malloc(ctx, sizeof(Vector2)))) {
            *s = data;
            JS_SetOpaque(obj, s);
        }
        return obj;
    }

    static void js_Vector2_finalizer(JSRuntime *rt, JSValue val) noexcept {
        if (auto* s = static_cast<Vector2*>(JS_GetOpaque(val, js_Vector2_class_id))) {
            js_free_rt(rt, s);
        }
    }

    // Getter for x
    static JSValue js_Vector2_get_x(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Vector2*>(JS_GetOpaque2(ctx, this_val, js_Vector2_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->x));
    }

    // Setter for x
    static JSValue js_Vector2_set_x(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Vector2*>(JS_GetOpaque2(ctx, this_val, js_Vector2_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->x = static_cast<float>(temp);
        return JS_UNDEFINED;
    }

    // Getter for y
    static JSValue js_Vector2_get_y(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Vector2*>(JS_GetOpaque2(ctx, this_val, js_Vector2_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->y));
    }

    // Setter for y
    static JSValue js_Vector2_set_y(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Vector2*>(JS_GetOpaque2(ctx, this_val, js_Vector2_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->y = static_cast<float>(temp);
        return JS_UNDEFINED;
    }


    // Constructor for Vector2
    static JSValue js_Vector2_constructor(JSContext *ctx, JSValueConst new_target, int argc, JSValueConst *argv) {
        
        // Expect either 0 arguments (default constructor) or all fields provided
        if (argc != 0 && argc != 2) {
            return JS_ThrowTypeError(ctx, "Expected either 0 arguments or exactly 2 arguments for Vector2 constructor");
        }
        
        Vector2 data = {}; // Initialize with defaults

        // Only populate if the user provides all fields 
        if (argc == 2) {
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[0])) {
                    data.x = static_cast<float>(temp); 
                }
            }
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[1])) {
                    data.y = static_cast<float>(temp); 
                }
            }
        }

        return JS_NewVector2(ctx, data);
    }

    constexpr JSCFunctionListEntry js_Vector2_proto_funcs[] = {
        JS_CGETSET_DEF("x", js_Vector2_get_x, js_Vector2_set_x),
        JS_CGETSET_DEF("y", js_Vector2_get_y, js_Vector2_set_y),
    };

    static void InitVector2Binding(JSContext *ctx, JSValue ns) {
        JSRuntime *rt = JS_GetRuntime(ctx);
        if (js_Vector2_class_id == 0) {
            JS_NewClassID(rt, &js_Vector2_class_id);
        }

        JSClassDef def{ .class_name = "Vector2", .finalizer = js_Vector2_finalizer };
        JS_NewClass(rt, js_Vector2_class_id, &def);

        JSValue proto = JS_NewObject(ctx);
        JS_SetPropertyFunctionList(ctx, proto, js_Vector2_proto_funcs, 2);
        JS_SetClassProto(ctx, js_Vector2_class_id, proto);

        // Create the constructor function and attach it to the namespace
        JSValue ctor = JS_NewCFunction2(ctx, js_Vector2_constructor, "Vector2", 2, JS_CFUNC_constructor, 0);
        JS_SetConstructor(ctx, ctor, proto);


        JS_SetPropertyStr(ctx, ns, "Vector2", ctor);
    }

    JSValue JS_NewVector3(JSContext *ctx, Vector3 data) {
        const JSValue obj = JS_NewObjectClass(ctx, js_Vector3_class_id);
        if (auto* s = static_cast<Vector3*>(js_malloc(ctx, sizeof(Vector3)))) {
            *s = data;
            JS_SetOpaque(obj, s);
        }
        return obj;
    }

    static void js_Vector3_finalizer(JSRuntime *rt, JSValue val) noexcept {
        if (auto* s = static_cast<Vector3*>(JS_GetOpaque(val, js_Vector3_class_id))) {
            js_free_rt(rt, s);
        }
    }

    // Getter for x
    static JSValue js_Vector3_get_x(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Vector3*>(JS_GetOpaque2(ctx, this_val, js_Vector3_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->x));
    }

    // Setter for x
    static JSValue js_Vector3_set_x(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Vector3*>(JS_GetOpaque2(ctx, this_val, js_Vector3_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->x = static_cast<float>(temp);
        return JS_UNDEFINED;
    }

    // Getter for y
    static JSValue js_Vector3_get_y(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Vector3*>(JS_GetOpaque2(ctx, this_val, js_Vector3_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->y));
    }

    // Setter for y
    static JSValue js_Vector3_set_y(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Vector3*>(JS_GetOpaque2(ctx, this_val, js_Vector3_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->y = static_cast<float>(temp);
        return JS_UNDEFINED;
    }

    // Getter for z
    static JSValue js_Vector3_get_z(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Vector3*>(JS_GetOpaque2(ctx, this_val, js_Vector3_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->z));
    }

    // Setter for z
    static JSValue js_Vector3_set_z(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Vector3*>(JS_GetOpaque2(ctx, this_val, js_Vector3_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->z = static_cast<float>(temp);
        return JS_UNDEFINED;
    }


    // Constructor for Vector3
    static JSValue js_Vector3_constructor(JSContext *ctx, JSValueConst new_target, int argc, JSValueConst *argv) {
        
        // Expect either 0 arguments (default constructor) or all fields provided
        if (argc != 0 && argc != 3) {
            return JS_ThrowTypeError(ctx, "Expected either 0 arguments or exactly 3 arguments for Vector3 constructor");
        }
        
        Vector3 data = {}; // Initialize with defaults

        // Only populate if the user provides all fields 
        if (argc == 3) {
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[0])) {
                    data.x = static_cast<float>(temp); 
                }
            }
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[1])) {
                    data.y = static_cast<float>(temp); 
                }
            }
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[2])) {
                    data.z = static_cast<float>(temp); 
                }
            }
        }

        return JS_NewVector3(ctx, data);
    }

    constexpr JSCFunctionListEntry js_Vector3_proto_funcs[] = {
        JS_CGETSET_DEF("x", js_Vector3_get_x, js_Vector3_set_x),
        JS_CGETSET_DEF("y", js_Vector3_get_y, js_Vector3_set_y),
        JS_CGETSET_DEF("z", js_Vector3_get_z, js_Vector3_set_z),
    };

    static void InitVector3Binding(JSContext *ctx, JSValue ns) {
        JSRuntime *rt = JS_GetRuntime(ctx);
        if (js_Vector3_class_id == 0) {
            JS_NewClassID(rt, &js_Vector3_class_id);
        }

        JSClassDef def{ .class_name = "Vector3", .finalizer = js_Vector3_finalizer };
        JS_NewClass(rt, js_Vector3_class_id, &def);

        JSValue proto = JS_NewObject(ctx);
        JS_SetPropertyFunctionList(ctx, proto, js_Vector3_proto_funcs, 3);
        JS_SetClassProto(ctx, js_Vector3_class_id, proto);

        // Create the constructor function and attach it to the namespace
        JSValue ctor = JS_NewCFunction2(ctx, js_Vector3_constructor, "Vector3", 3, JS_CFUNC_constructor, 0);
        JS_SetConstructor(ctx, ctor, proto);


        JS_SetPropertyStr(ctx, ns, "Vector3", ctor);
    }

    JSValue JS_NewVector4(JSContext *ctx, Vector4 data) {
        const JSValue obj = JS_NewObjectClass(ctx, js_Vector4_class_id);
        if (auto* s = static_cast<Vector4*>(js_malloc(ctx, sizeof(Vector4)))) {
            *s = data;
            JS_SetOpaque(obj, s);
        }
        return obj;
    }

    static void js_Vector4_finalizer(JSRuntime *rt, JSValue val) noexcept {
        if (auto* s = static_cast<Vector4*>(JS_GetOpaque(val, js_Vector4_class_id))) {
            js_free_rt(rt, s);
        }
    }

    // Getter for x
    static JSValue js_Vector4_get_x(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Vector4*>(JS_GetOpaque2(ctx, this_val, js_Vector4_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->x));
    }

    // Setter for x
    static JSValue js_Vector4_set_x(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Vector4*>(JS_GetOpaque2(ctx, this_val, js_Vector4_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->x = static_cast<float>(temp);
        return JS_UNDEFINED;
    }

    // Getter for y
    static JSValue js_Vector4_get_y(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Vector4*>(JS_GetOpaque2(ctx, this_val, js_Vector4_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->y));
    }

    // Setter for y
    static JSValue js_Vector4_set_y(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Vector4*>(JS_GetOpaque2(ctx, this_val, js_Vector4_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->y = static_cast<float>(temp);
        return JS_UNDEFINED;
    }

    // Getter for z
    static JSValue js_Vector4_get_z(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Vector4*>(JS_GetOpaque2(ctx, this_val, js_Vector4_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->z));
    }

    // Setter for z
    static JSValue js_Vector4_set_z(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Vector4*>(JS_GetOpaque2(ctx, this_val, js_Vector4_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->z = static_cast<float>(temp);
        return JS_UNDEFINED;
    }

    // Getter for w
    static JSValue js_Vector4_get_w(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Vector4*>(JS_GetOpaque2(ctx, this_val, js_Vector4_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->w));
    }

    // Setter for w
    static JSValue js_Vector4_set_w(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Vector4*>(JS_GetOpaque2(ctx, this_val, js_Vector4_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->w = static_cast<float>(temp);
        return JS_UNDEFINED;
    }


    // Constructor for Vector4
    static JSValue js_Vector4_constructor(JSContext *ctx, JSValueConst new_target, int argc, JSValueConst *argv) {
        
        // Expect either 0 arguments (default constructor) or all fields provided
        if (argc != 0 && argc != 4) {
            return JS_ThrowTypeError(ctx, "Expected either 0 arguments or exactly 4 arguments for Vector4 constructor");
        }
        
        Vector4 data = {}; // Initialize with defaults

        // Only populate if the user provides all fields 
        if (argc == 4) {
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[0])) {
                    data.x = static_cast<float>(temp); 
                }
            }
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[1])) {
                    data.y = static_cast<float>(temp); 
                }
            }
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[2])) {
                    data.z = static_cast<float>(temp); 
                }
            }
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[3])) {
                    data.w = static_cast<float>(temp); 
                }
            }
        }

        return JS_NewVector4(ctx, data);
    }

    constexpr JSCFunctionListEntry js_Vector4_proto_funcs[] = {
        JS_CGETSET_DEF("x", js_Vector4_get_x, js_Vector4_set_x),
        JS_CGETSET_DEF("y", js_Vector4_get_y, js_Vector4_set_y),
        JS_CGETSET_DEF("z", js_Vector4_get_z, js_Vector4_set_z),
        JS_CGETSET_DEF("w", js_Vector4_get_w, js_Vector4_set_w),
    };

    static void InitVector4Binding(JSContext *ctx, JSValue ns) {
        JSRuntime *rt = JS_GetRuntime(ctx);
        if (js_Vector4_class_id == 0) {
            JS_NewClassID(rt, &js_Vector4_class_id);
        }

        JSClassDef def{ .class_name = "Vector4", .finalizer = js_Vector4_finalizer };
        JS_NewClass(rt, js_Vector4_class_id, &def);

        JSValue proto = JS_NewObject(ctx);
        JS_SetPropertyFunctionList(ctx, proto, js_Vector4_proto_funcs, 4);
        JS_SetClassProto(ctx, js_Vector4_class_id, proto);

        // Create the constructor function and attach it to the namespace
        JSValue ctor = JS_NewCFunction2(ctx, js_Vector4_constructor, "Vector4", 4, JS_CFUNC_constructor, 0);
        JS_SetConstructor(ctx, ctor, proto);


        JS_SetPropertyStr(ctx, ns, "Vector4", ctor);
    }

    JSValue JS_NewMatrix(JSContext *ctx, Matrix data) {
        const JSValue obj = JS_NewObjectClass(ctx, js_Matrix_class_id);
        if (auto* s = static_cast<Matrix*>(js_malloc(ctx, sizeof(Matrix)))) {
            *s = data;
            JS_SetOpaque(obj, s);
        }
        return obj;
    }

    static void js_Matrix_finalizer(JSRuntime *rt, JSValue val) noexcept {
        if (auto* s = static_cast<Matrix*>(JS_GetOpaque(val, js_Matrix_class_id))) {
            js_free_rt(rt, s);
        }
    }

    // Getter for m0
    static JSValue js_Matrix_get_m0(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->m0));
    }

    // Setter for m0
    static JSValue js_Matrix_set_m0(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->m0 = static_cast<float>(temp);
        return JS_UNDEFINED;
    }

    // Getter for m4
    static JSValue js_Matrix_get_m4(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->m4));
    }

    // Setter for m4
    static JSValue js_Matrix_set_m4(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->m4 = static_cast<float>(temp);
        return JS_UNDEFINED;
    }

    // Getter for m8
    static JSValue js_Matrix_get_m8(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->m8));
    }

    // Setter for m8
    static JSValue js_Matrix_set_m8(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->m8 = static_cast<float>(temp);
        return JS_UNDEFINED;
    }

    // Getter for m12
    static JSValue js_Matrix_get_m12(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->m12));
    }

    // Setter for m12
    static JSValue js_Matrix_set_m12(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->m12 = static_cast<float>(temp);
        return JS_UNDEFINED;
    }

    // Getter for m1
    static JSValue js_Matrix_get_m1(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->m1));
    }

    // Setter for m1
    static JSValue js_Matrix_set_m1(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->m1 = static_cast<float>(temp);
        return JS_UNDEFINED;
    }

    // Getter for m5
    static JSValue js_Matrix_get_m5(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->m5));
    }

    // Setter for m5
    static JSValue js_Matrix_set_m5(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->m5 = static_cast<float>(temp);
        return JS_UNDEFINED;
    }

    // Getter for m9
    static JSValue js_Matrix_get_m9(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->m9));
    }

    // Setter for m9
    static JSValue js_Matrix_set_m9(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->m9 = static_cast<float>(temp);
        return JS_UNDEFINED;
    }

    // Getter for m13
    static JSValue js_Matrix_get_m13(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->m13));
    }

    // Setter for m13
    static JSValue js_Matrix_set_m13(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->m13 = static_cast<float>(temp);
        return JS_UNDEFINED;
    }

    // Getter for m2
    static JSValue js_Matrix_get_m2(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->m2));
    }

    // Setter for m2
    static JSValue js_Matrix_set_m2(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->m2 = static_cast<float>(temp);
        return JS_UNDEFINED;
    }

    // Getter for m6
    static JSValue js_Matrix_get_m6(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->m6));
    }

    // Setter for m6
    static JSValue js_Matrix_set_m6(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->m6 = static_cast<float>(temp);
        return JS_UNDEFINED;
    }

    // Getter for m10
    static JSValue js_Matrix_get_m10(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->m10));
    }

    // Setter for m10
    static JSValue js_Matrix_set_m10(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->m10 = static_cast<float>(temp);
        return JS_UNDEFINED;
    }

    // Getter for m14
    static JSValue js_Matrix_get_m14(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->m14));
    }

    // Setter for m14
    static JSValue js_Matrix_set_m14(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->m14 = static_cast<float>(temp);
        return JS_UNDEFINED;
    }

    // Getter for m3
    static JSValue js_Matrix_get_m3(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->m3));
    }

    // Setter for m3
    static JSValue js_Matrix_set_m3(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->m3 = static_cast<float>(temp);
        return JS_UNDEFINED;
    }

    // Getter for m7
    static JSValue js_Matrix_get_m7(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->m7));
    }

    // Setter for m7
    static JSValue js_Matrix_set_m7(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->m7 = static_cast<float>(temp);
        return JS_UNDEFINED;
    }

    // Getter for m11
    static JSValue js_Matrix_get_m11(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->m11));
    }

    // Setter for m11
    static JSValue js_Matrix_set_m11(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->m11 = static_cast<float>(temp);
        return JS_UNDEFINED;
    }

    // Getter for m15
    static JSValue js_Matrix_get_m15(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->m15));
    }

    // Setter for m15
    static JSValue js_Matrix_set_m15(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Matrix*>(JS_GetOpaque2(ctx, this_val, js_Matrix_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->m15 = static_cast<float>(temp);
        return JS_UNDEFINED;
    }


    // Constructor for Matrix
    static JSValue js_Matrix_constructor(JSContext *ctx, JSValueConst new_target, int argc, JSValueConst *argv) {
        
        // Expect either 0 arguments (default constructor) or all fields provided
        if (argc != 0 && argc != 16) {
            return JS_ThrowTypeError(ctx, "Expected either 0 arguments or exactly 16 arguments for Matrix constructor");
        }
        
        Matrix data = {}; // Initialize with defaults

        // Only populate if the user provides all fields 
        if (argc == 16) {
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[0])) {
                    data.m0 = static_cast<float>(temp); 
                }
            }
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[1])) {
                    data.m4 = static_cast<float>(temp); 
                }
            }
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[2])) {
                    data.m8 = static_cast<float>(temp); 
                }
            }
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[3])) {
                    data.m12 = static_cast<float>(temp); 
                }
            }
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[4])) {
                    data.m1 = static_cast<float>(temp); 
                }
            }
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[5])) {
                    data.m5 = static_cast<float>(temp); 
                }
            }
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[6])) {
                    data.m9 = static_cast<float>(temp); 
                }
            }
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[7])) {
                    data.m13 = static_cast<float>(temp); 
                }
            }
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[8])) {
                    data.m2 = static_cast<float>(temp); 
                }
            }
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[9])) {
                    data.m6 = static_cast<float>(temp); 
                }
            }
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[10])) {
                    data.m10 = static_cast<float>(temp); 
                }
            }
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[11])) {
                    data.m14 = static_cast<float>(temp); 
                }
            }
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[12])) {
                    data.m3 = static_cast<float>(temp); 
                }
            }
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[13])) {
                    data.m7 = static_cast<float>(temp); 
                }
            }
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[14])) {
                    data.m11 = static_cast<float>(temp); 
                }
            }
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[15])) {
                    data.m15 = static_cast<float>(temp); 
                }
            }
        }

        return JS_NewMatrix(ctx, data);
    }

    constexpr JSCFunctionListEntry js_Matrix_proto_funcs[] = {
        JS_CGETSET_DEF("m0", js_Matrix_get_m0, js_Matrix_set_m0),
        JS_CGETSET_DEF("m4", js_Matrix_get_m4, js_Matrix_set_m4),
        JS_CGETSET_DEF("m8", js_Matrix_get_m8, js_Matrix_set_m8),
        JS_CGETSET_DEF("m12", js_Matrix_get_m12, js_Matrix_set_m12),
        JS_CGETSET_DEF("m1", js_Matrix_get_m1, js_Matrix_set_m1),
        JS_CGETSET_DEF("m5", js_Matrix_get_m5, js_Matrix_set_m5),
        JS_CGETSET_DEF("m9", js_Matrix_get_m9, js_Matrix_set_m9),
        JS_CGETSET_DEF("m13", js_Matrix_get_m13, js_Matrix_set_m13),
        JS_CGETSET_DEF("m2", js_Matrix_get_m2, js_Matrix_set_m2),
        JS_CGETSET_DEF("m6", js_Matrix_get_m6, js_Matrix_set_m6),
        JS_CGETSET_DEF("m10", js_Matrix_get_m10, js_Matrix_set_m10),
        JS_CGETSET_DEF("m14", js_Matrix_get_m14, js_Matrix_set_m14),
        JS_CGETSET_DEF("m3", js_Matrix_get_m3, js_Matrix_set_m3),
        JS_CGETSET_DEF("m7", js_Matrix_get_m7, js_Matrix_set_m7),
        JS_CGETSET_DEF("m11", js_Matrix_get_m11, js_Matrix_set_m11),
        JS_CGETSET_DEF("m15", js_Matrix_get_m15, js_Matrix_set_m15),
    };

    static void InitMatrixBinding(JSContext *ctx, JSValue ns) {
        JSRuntime *rt = JS_GetRuntime(ctx);
        if (js_Matrix_class_id == 0) {
            JS_NewClassID(rt, &js_Matrix_class_id);
        }

        JSClassDef def{ .class_name = "Matrix", .finalizer = js_Matrix_finalizer };
        JS_NewClass(rt, js_Matrix_class_id, &def);

        JSValue proto = JS_NewObject(ctx);
        JS_SetPropertyFunctionList(ctx, proto, js_Matrix_proto_funcs, 16);
        JS_SetClassProto(ctx, js_Matrix_class_id, proto);

        // Create the constructor function and attach it to the namespace
        JSValue ctor = JS_NewCFunction2(ctx, js_Matrix_constructor, "Matrix", 16, JS_CFUNC_constructor, 0);
        JS_SetConstructor(ctx, ctor, proto);


        JS_SetPropertyStr(ctx, ns, "Matrix", ctor);
    }

    JSValue JS_NewColor(JSContext *ctx, Color data) {
        const JSValue obj = JS_NewObjectClass(ctx, js_Color_class_id);
        if (auto* s = static_cast<Color*>(js_malloc(ctx, sizeof(Color)))) {
            *s = data;
            JS_SetOpaque(obj, s);
        }
        return obj;
    }

    static void js_Color_finalizer(JSRuntime *rt, JSValue val) noexcept {
        if (auto* s = static_cast<Color*>(JS_GetOpaque(val, js_Color_class_id))) {
            js_free_rt(rt, s);
        }
    }

    // Getter for r
    static JSValue js_Color_get_r(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Color*>(JS_GetOpaque2(ctx, this_val, js_Color_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewInt32(ctx, static_cast<int32_t>(s->r));
    }

    // Setter for r
    static JSValue js_Color_set_r(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Color*>(JS_GetOpaque2(ctx, this_val, js_Color_class_id));
        if (!s) return JS_EXCEPTION;

        int32_t temp;
        if (JS_ToInt32(ctx, &temp, val)) return JS_EXCEPTION;
        s->r = static_cast<unsigned char>(temp);
        return JS_UNDEFINED;
    }

    // Getter for g
    static JSValue js_Color_get_g(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Color*>(JS_GetOpaque2(ctx, this_val, js_Color_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewInt32(ctx, static_cast<int32_t>(s->g));
    }

    // Setter for g
    static JSValue js_Color_set_g(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Color*>(JS_GetOpaque2(ctx, this_val, js_Color_class_id));
        if (!s) return JS_EXCEPTION;

        int32_t temp;
        if (JS_ToInt32(ctx, &temp, val)) return JS_EXCEPTION;
        s->g = static_cast<unsigned char>(temp);
        return JS_UNDEFINED;
    }

    // Getter for b
    static JSValue js_Color_get_b(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Color*>(JS_GetOpaque2(ctx, this_val, js_Color_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewInt32(ctx, static_cast<int32_t>(s->b));
    }

    // Setter for b
    static JSValue js_Color_set_b(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Color*>(JS_GetOpaque2(ctx, this_val, js_Color_class_id));
        if (!s) return JS_EXCEPTION;

        int32_t temp;
        if (JS_ToInt32(ctx, &temp, val)) return JS_EXCEPTION;
        s->b = static_cast<unsigned char>(temp);
        return JS_UNDEFINED;
    }

    // Getter for a
    static JSValue js_Color_get_a(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Color*>(JS_GetOpaque2(ctx, this_val, js_Color_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewInt32(ctx, static_cast<int32_t>(s->a));
    }

    // Setter for a
    static JSValue js_Color_set_a(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Color*>(JS_GetOpaque2(ctx, this_val, js_Color_class_id));
        if (!s) return JS_EXCEPTION;

        int32_t temp;
        if (JS_ToInt32(ctx, &temp, val)) return JS_EXCEPTION;
        s->a = static_cast<unsigned char>(temp);
        return JS_UNDEFINED;
    }


    // Constructor for Color
    static JSValue js_Color_constructor(JSContext *ctx, JSValueConst new_target, int argc, JSValueConst *argv) {
        
        // Expect either 0 arguments (default constructor) or all fields provided
        if (argc != 0 && argc != 4) {
            return JS_ThrowTypeError(ctx, "Expected either 0 arguments or exactly 4 arguments for Color constructor");
        }
        
        Color data = {}; // Initialize with defaults

        // Only populate if the user provides all fields 
        if (argc == 4) {
            {
                int32_t temp;
                if (!JS_ToInt32(ctx, &temp, argv[0])) {
                    data.r = static_cast<unsigned char>(temp); 
                }
            }
            {
                int32_t temp;
                if (!JS_ToInt32(ctx, &temp, argv[1])) {
                    data.g = static_cast<unsigned char>(temp); 
                }
            }
            {
                int32_t temp;
                if (!JS_ToInt32(ctx, &temp, argv[2])) {
                    data.b = static_cast<unsigned char>(temp); 
                }
            }
            {
                int32_t temp;
                if (!JS_ToInt32(ctx, &temp, argv[3])) {
                    data.a = static_cast<unsigned char>(temp); 
                }
            }
        }

        return JS_NewColor(ctx, data);
    }

    constexpr JSCFunctionListEntry js_Color_proto_funcs[] = {
        JS_CGETSET_DEF("r", js_Color_get_r, js_Color_set_r),
        JS_CGETSET_DEF("g", js_Color_get_g, js_Color_set_g),
        JS_CGETSET_DEF("b", js_Color_get_b, js_Color_set_b),
        JS_CGETSET_DEF("a", js_Color_get_a, js_Color_set_a),
    };

    static void InitColorBinding(JSContext *ctx, JSValue ns) {
        JSRuntime *rt = JS_GetRuntime(ctx);
        if (js_Color_class_id == 0) {
            JS_NewClassID(rt, &js_Color_class_id);
        }

        JSClassDef def{ .class_name = "Color", .finalizer = js_Color_finalizer };
        JS_NewClass(rt, js_Color_class_id, &def);

        JSValue proto = JS_NewObject(ctx);
        JS_SetPropertyFunctionList(ctx, proto, js_Color_proto_funcs, 4);
        JS_SetClassProto(ctx, js_Color_class_id, proto);

        // Create the constructor function and attach it to the namespace
        JSValue ctor = JS_NewCFunction2(ctx, js_Color_constructor, "Color", 4, JS_CFUNC_constructor, 0);
        JS_SetConstructor(ctx, ctor, proto);

        JS_SetPropertyStr(ctx, ctor, "LIGHTGRAY", JS_NewColor(ctx, Color{ 200, 200, 200, 255 }));
        JS_SetPropertyStr(ctx, ctor, "GRAY", JS_NewColor(ctx, Color{ 130, 130, 130, 255 }));
        JS_SetPropertyStr(ctx, ctor, "DARKGRAY", JS_NewColor(ctx, Color{ 80, 80, 80, 255 }));
        JS_SetPropertyStr(ctx, ctor, "YELLOW", JS_NewColor(ctx, Color{ 253, 249, 0, 255 }));
        JS_SetPropertyStr(ctx, ctor, "GOLD", JS_NewColor(ctx, Color{ 255, 203, 0, 255 }));
        JS_SetPropertyStr(ctx, ctor, "ORANGE", JS_NewColor(ctx, Color{ 255, 161, 0, 255 }));
        JS_SetPropertyStr(ctx, ctor, "PINK", JS_NewColor(ctx, Color{ 255, 109, 194, 255 }));
        JS_SetPropertyStr(ctx, ctor, "RED", JS_NewColor(ctx, Color{ 230, 41, 55, 255 }));
        JS_SetPropertyStr(ctx, ctor, "MAROON", JS_NewColor(ctx, Color{ 190, 33, 55, 255 }));
        JS_SetPropertyStr(ctx, ctor, "GREEN", JS_NewColor(ctx, Color{ 0, 228, 48, 255 }));
        JS_SetPropertyStr(ctx, ctor, "LIME", JS_NewColor(ctx, Color{ 0, 158, 47, 255 }));
        JS_SetPropertyStr(ctx, ctor, "DARKGREEN", JS_NewColor(ctx, Color{ 0, 117, 44, 255 }));
        JS_SetPropertyStr(ctx, ctor, "SKYBLUE", JS_NewColor(ctx, Color{ 102, 191, 255, 255 }));
        JS_SetPropertyStr(ctx, ctor, "BLUE", JS_NewColor(ctx, Color{ 0, 121, 241, 255 }));
        JS_SetPropertyStr(ctx, ctor, "DARKBLUE", JS_NewColor(ctx, Color{ 0, 82, 172, 255 }));
        JS_SetPropertyStr(ctx, ctor, "PURPLE", JS_NewColor(ctx, Color{ 200, 122, 255, 255 }));
        JS_SetPropertyStr(ctx, ctor, "VIOLET", JS_NewColor(ctx, Color{ 135, 60, 190, 255 }));
        JS_SetPropertyStr(ctx, ctor, "DARKPURPLE", JS_NewColor(ctx, Color{ 112, 31, 126, 255 }));
        JS_SetPropertyStr(ctx, ctor, "BEIGE", JS_NewColor(ctx, Color{ 211, 176, 131, 255 }));
        JS_SetPropertyStr(ctx, ctor, "BROWN", JS_NewColor(ctx, Color{ 127, 106, 79, 255 }));
        JS_SetPropertyStr(ctx, ctor, "DARKBROWN", JS_NewColor(ctx, Color{ 76, 63, 47, 255 }));
        JS_SetPropertyStr(ctx, ctor, "WHITE", JS_NewColor(ctx, Color{ 255, 255, 255, 255 }));
        JS_SetPropertyStr(ctx, ctor, "BLACK", JS_NewColor(ctx, Color{ 0, 0, 0, 255 }));
        JS_SetPropertyStr(ctx, ctor, "BLANK", JS_NewColor(ctx, Color{ 0, 0, 0, 0 }));
        JS_SetPropertyStr(ctx, ctor, "MAGENTA", JS_NewColor(ctx, Color{ 255, 0, 255, 255 }));
        JS_SetPropertyStr(ctx, ctor, "RAYWHITE", JS_NewColor(ctx, Color{ 245, 245, 245, 255 }));

        JS_SetPropertyStr(ctx, ns, "Color", ctor);
    }

    JSValue JS_NewRectangle(JSContext *ctx, Rectangle data) {
        const JSValue obj = JS_NewObjectClass(ctx, js_Rectangle_class_id);
        if (auto* s = static_cast<Rectangle*>(js_malloc(ctx, sizeof(Rectangle)))) {
            *s = data;
            JS_SetOpaque(obj, s);
        }
        return obj;
    }

    static void js_Rectangle_finalizer(JSRuntime *rt, JSValue val) noexcept {
        if (auto* s = static_cast<Rectangle*>(JS_GetOpaque(val, js_Rectangle_class_id))) {
            js_free_rt(rt, s);
        }
    }

    // Getter for x
    static JSValue js_Rectangle_get_x(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Rectangle*>(JS_GetOpaque2(ctx, this_val, js_Rectangle_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->x));
    }

    // Setter for x
    static JSValue js_Rectangle_set_x(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Rectangle*>(JS_GetOpaque2(ctx, this_val, js_Rectangle_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->x = static_cast<float>(temp);
        return JS_UNDEFINED;
    }

    // Getter for y
    static JSValue js_Rectangle_get_y(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Rectangle*>(JS_GetOpaque2(ctx, this_val, js_Rectangle_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->y));
    }

    // Setter for y
    static JSValue js_Rectangle_set_y(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Rectangle*>(JS_GetOpaque2(ctx, this_val, js_Rectangle_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->y = static_cast<float>(temp);
        return JS_UNDEFINED;
    }

    // Getter for width
    static JSValue js_Rectangle_get_width(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Rectangle*>(JS_GetOpaque2(ctx, this_val, js_Rectangle_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->width));
    }

    // Setter for width
    static JSValue js_Rectangle_set_width(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Rectangle*>(JS_GetOpaque2(ctx, this_val, js_Rectangle_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->width = static_cast<float>(temp);
        return JS_UNDEFINED;
    }

    // Getter for height
    static JSValue js_Rectangle_get_height(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Rectangle*>(JS_GetOpaque2(ctx, this_val, js_Rectangle_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewFloat64(ctx, static_cast<double>(s->height));
    }

    // Setter for height
    static JSValue js_Rectangle_set_height(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Rectangle*>(JS_GetOpaque2(ctx, this_val, js_Rectangle_class_id));
        if (!s) return JS_EXCEPTION;

        double temp;
        if (JS_ToFloat64(ctx, &temp, val)) return JS_EXCEPTION;
        s->height = static_cast<float>(temp);
        return JS_UNDEFINED;
    }


    // Constructor for Rectangle
    static JSValue js_Rectangle_constructor(JSContext *ctx, JSValueConst new_target, int argc, JSValueConst *argv) {
        
        // Expect either 0 arguments (default constructor) or all fields provided
        if (argc != 0 && argc != 4) {
            return JS_ThrowTypeError(ctx, "Expected either 0 arguments or exactly 4 arguments for Rectangle constructor");
        }
        
        Rectangle data = {}; // Initialize with defaults

        // Only populate if the user provides all fields 
        if (argc == 4) {
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[0])) {
                    data.x = static_cast<float>(temp); 
                }
            }
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[1])) {
                    data.y = static_cast<float>(temp); 
                }
            }
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[2])) {
                    data.width = static_cast<float>(temp); 
                }
            }
            {
                double temp;
                if (!JS_ToFloat64(ctx, &temp, argv[3])) {
                    data.height = static_cast<float>(temp); 
                }
            }
        }

        return JS_NewRectangle(ctx, data);
    }

    constexpr JSCFunctionListEntry js_Rectangle_proto_funcs[] = {
        JS_CGETSET_DEF("x", js_Rectangle_get_x, js_Rectangle_set_x),
        JS_CGETSET_DEF("y", js_Rectangle_get_y, js_Rectangle_set_y),
        JS_CGETSET_DEF("width", js_Rectangle_get_width, js_Rectangle_set_width),
        JS_CGETSET_DEF("height", js_Rectangle_get_height, js_Rectangle_set_height),
    };

    static void InitRectangleBinding(JSContext *ctx, JSValue ns) {
        JSRuntime *rt = JS_GetRuntime(ctx);
        if (js_Rectangle_class_id == 0) {
            JS_NewClassID(rt, &js_Rectangle_class_id);
        }

        JSClassDef def{ .class_name = "Rectangle", .finalizer = js_Rectangle_finalizer };
        JS_NewClass(rt, js_Rectangle_class_id, &def);

        JSValue proto = JS_NewObject(ctx);
        JS_SetPropertyFunctionList(ctx, proto, js_Rectangle_proto_funcs, 4);
        JS_SetClassProto(ctx, js_Rectangle_class_id, proto);

        // Create the constructor function and attach it to the namespace
        JSValue ctor = JS_NewCFunction2(ctx, js_Rectangle_constructor, "Rectangle", 4, JS_CFUNC_constructor, 0);
        JS_SetConstructor(ctx, ctor, proto);


        JS_SetPropertyStr(ctx, ns, "Rectangle", ctor);
    }

    JSValue JS_NewImage(JSContext *ctx, Image data) {
        const JSValue obj = JS_NewObjectClass(ctx, js_Image_class_id);
        if (auto* s = static_cast<Image*>(js_malloc(ctx, sizeof(Image)))) {
            *s = data;
            JS_SetOpaque(obj, s);
        }
        return obj;
    }

    static void js_Image_finalizer(JSRuntime *rt, JSValue val) noexcept {
        if (auto* s = static_cast<Image*>(JS_GetOpaque(val, js_Image_class_id))) {
            js_free_rt(rt, s);
        }
    }

    // Getter for data
    static JSValue js_Image_get_data(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Image*>(JS_GetOpaque2(ctx, this_val, js_Image_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewInt64(ctx, reinterpret_cast<int64_t>(s->data));
    }

    // Setter for data
    static JSValue js_Image_set_data(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Image*>(JS_GetOpaque2(ctx, this_val, js_Image_class_id));
        if (!s) return JS_EXCEPTION;

        int64_t ptr_addr;
        if (JS_ToInt64(ctx, &ptr_addr, val)) return JS_EXCEPTION;
        s->data = reinterpret_cast<void *>(ptr_addr);
        return JS_UNDEFINED;
    }

    // Getter for width
    static JSValue js_Image_get_width(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Image*>(JS_GetOpaque2(ctx, this_val, js_Image_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewInt32(ctx, static_cast<int32_t>(s->width));
    }

    // Setter for width
    static JSValue js_Image_set_width(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Image*>(JS_GetOpaque2(ctx, this_val, js_Image_class_id));
        if (!s) return JS_EXCEPTION;

        int32_t temp;
        if (JS_ToInt32(ctx, &temp, val)) return JS_EXCEPTION;
        s->width = static_cast<int>(temp);
        return JS_UNDEFINED;
    }

    // Getter for height
    static JSValue js_Image_get_height(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Image*>(JS_GetOpaque2(ctx, this_val, js_Image_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewInt32(ctx, static_cast<int32_t>(s->height));
    }

    // Setter for height
    static JSValue js_Image_set_height(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Image*>(JS_GetOpaque2(ctx, this_val, js_Image_class_id));
        if (!s) return JS_EXCEPTION;

        int32_t temp;
        if (JS_ToInt32(ctx, &temp, val)) return JS_EXCEPTION;
        s->height = static_cast<int>(temp);
        return JS_UNDEFINED;
    }

    // Getter for mipmaps
    static JSValue js_Image_get_mipmaps(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Image*>(JS_GetOpaque2(ctx, this_val, js_Image_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewInt32(ctx, static_cast<int32_t>(s->mipmaps));
    }

    // Setter for mipmaps
    static JSValue js_Image_set_mipmaps(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Image*>(JS_GetOpaque2(ctx, this_val, js_Image_class_id));
        if (!s) return JS_EXCEPTION;

        int32_t temp;
        if (JS_ToInt32(ctx, &temp, val)) return JS_EXCEPTION;
        s->mipmaps = static_cast<int>(temp);
        return JS_UNDEFINED;
    }

    // Getter for format
    static JSValue js_Image_get_format(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Image*>(JS_GetOpaque2(ctx, this_val, js_Image_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewInt32(ctx, static_cast<int32_t>(s->format));
    }

    // Setter for format
    static JSValue js_Image_set_format(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Image*>(JS_GetOpaque2(ctx, this_val, js_Image_class_id));
        if (!s) return JS_EXCEPTION;

        int32_t temp;
        if (JS_ToInt32(ctx, &temp, val)) return JS_EXCEPTION;
        s->format = static_cast<int>(temp);
        return JS_UNDEFINED;
    }


    // Constructor for Image
    static JSValue js_Image_constructor(JSContext *ctx, JSValueConst new_target, int argc, JSValueConst *argv) {
        
        // Expect either 0 arguments (default constructor) or all fields provided
        if (argc != 0 && argc != 5) {
            return JS_ThrowTypeError(ctx, "Expected either 0 arguments or exactly 5 arguments for Image constructor");
        }
        
        Image data = {}; // Initialize with defaults

        // Only populate if the user provides all fields 
        if (argc == 5) {
            {
                int64_t ptr_addr;
                if (!JS_ToInt64(ctx, &ptr_addr, argv[0])) {
                    data.data = reinterpret_cast<void *>(ptr_addr); 
                }
            }
            {
                int32_t temp;
                if (!JS_ToInt32(ctx, &temp, argv[1])) {
                    data.width = static_cast<int>(temp); 
                }
            }
            {
                int32_t temp;
                if (!JS_ToInt32(ctx, &temp, argv[2])) {
                    data.height = static_cast<int>(temp); 
                }
            }
            {
                int32_t temp;
                if (!JS_ToInt32(ctx, &temp, argv[3])) {
                    data.mipmaps = static_cast<int>(temp); 
                }
            }
            {
                int32_t temp;
                if (!JS_ToInt32(ctx, &temp, argv[4])) {
                    data.format = static_cast<int>(temp); 
                }
            }
        }

        return JS_NewImage(ctx, data);
    }

    constexpr JSCFunctionListEntry js_Image_proto_funcs[] = {
        JS_CGETSET_DEF("data", js_Image_get_data, js_Image_set_data),
        JS_CGETSET_DEF("width", js_Image_get_width, js_Image_set_width),
        JS_CGETSET_DEF("height", js_Image_get_height, js_Image_set_height),
        JS_CGETSET_DEF("mipmaps", js_Image_get_mipmaps, js_Image_set_mipmaps),
        JS_CGETSET_DEF("format", js_Image_get_format, js_Image_set_format),
    };

    static void InitImageBinding(JSContext *ctx, JSValue ns) {
        JSRuntime *rt = JS_GetRuntime(ctx);
        if (js_Image_class_id == 0) {
            JS_NewClassID(rt, &js_Image_class_id);
        }

        JSClassDef def{ .class_name = "Image", .finalizer = js_Image_finalizer };
        JS_NewClass(rt, js_Image_class_id, &def);

        JSValue proto = JS_NewObject(ctx);
        JS_SetPropertyFunctionList(ctx, proto, js_Image_proto_funcs, 5);
        JS_SetClassProto(ctx, js_Image_class_id, proto);

        // Create the constructor function and attach it to the namespace
        JSValue ctor = JS_NewCFunction2(ctx, js_Image_constructor, "Image", 5, JS_CFUNC_constructor, 0);
        JS_SetConstructor(ctx, ctor, proto);


        JS_SetPropertyStr(ctx, ns, "Image", ctor);
    }

    JSValue JS_NewTexture(JSContext *ctx, Texture data) {
        const JSValue obj = JS_NewObjectClass(ctx, js_Texture_class_id);
        if (auto* s = static_cast<Texture*>(js_malloc(ctx, sizeof(Texture)))) {
            *s = data;
            JS_SetOpaque(obj, s);
        }
        return obj;
    }

    static void js_Texture_finalizer(JSRuntime *rt, JSValue val) noexcept {
        if (auto* s = static_cast<Texture*>(JS_GetOpaque(val, js_Texture_class_id))) {
            js_free_rt(rt, s);
        }
    }

    // Getter for id
    static JSValue js_Texture_get_id(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Texture*>(JS_GetOpaque2(ctx, this_val, js_Texture_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewInt64(ctx, static_cast<int64_t>(s->id));
    }

    // Setter for id
    static JSValue js_Texture_set_id(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Texture*>(JS_GetOpaque2(ctx, this_val, js_Texture_class_id));
        if (!s) return JS_EXCEPTION;

        int64_t temp;
        if (JS_ToInt64(ctx, &temp, val)) return JS_EXCEPTION;
        s->id = static_cast<unsigned int>(temp);
        return JS_UNDEFINED;
    }

    // Getter for width
    static JSValue js_Texture_get_width(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Texture*>(JS_GetOpaque2(ctx, this_val, js_Texture_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewInt32(ctx, static_cast<int32_t>(s->width));
    }

    // Setter for width
    static JSValue js_Texture_set_width(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Texture*>(JS_GetOpaque2(ctx, this_val, js_Texture_class_id));
        if (!s) return JS_EXCEPTION;

        int32_t temp;
        if (JS_ToInt32(ctx, &temp, val)) return JS_EXCEPTION;
        s->width = static_cast<int>(temp);
        return JS_UNDEFINED;
    }

    // Getter for height
    static JSValue js_Texture_get_height(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Texture*>(JS_GetOpaque2(ctx, this_val, js_Texture_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewInt32(ctx, static_cast<int32_t>(s->height));
    }

    // Setter for height
    static JSValue js_Texture_set_height(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Texture*>(JS_GetOpaque2(ctx, this_val, js_Texture_class_id));
        if (!s) return JS_EXCEPTION;

        int32_t temp;
        if (JS_ToInt32(ctx, &temp, val)) return JS_EXCEPTION;
        s->height = static_cast<int>(temp);
        return JS_UNDEFINED;
    }

    // Getter for mipmaps
    static JSValue js_Texture_get_mipmaps(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Texture*>(JS_GetOpaque2(ctx, this_val, js_Texture_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewInt32(ctx, static_cast<int32_t>(s->mipmaps));
    }

    // Setter for mipmaps
    static JSValue js_Texture_set_mipmaps(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Texture*>(JS_GetOpaque2(ctx, this_val, js_Texture_class_id));
        if (!s) return JS_EXCEPTION;

        int32_t temp;
        if (JS_ToInt32(ctx, &temp, val)) return JS_EXCEPTION;
        s->mipmaps = static_cast<int>(temp);
        return JS_UNDEFINED;
    }

    // Getter for format
    static JSValue js_Texture_get_format(JSContext *ctx, JSValueConst this_val) noexcept {
        const auto* s = static_cast<Texture*>(JS_GetOpaque2(ctx, this_val, js_Texture_class_id));
        if (!s) return JS_EXCEPTION;
        return JS_NewInt32(ctx, static_cast<int32_t>(s->format));
    }

    // Setter for format
    static JSValue js_Texture_set_format(JSContext *ctx, JSValueConst this_val, JSValueConst val) noexcept {
        auto s = static_cast<Texture*>(JS_GetOpaque2(ctx, this_val, js_Texture_class_id));
        if (!s) return JS_EXCEPTION;

        int32_t temp;
        if (JS_ToInt32(ctx, &temp, val)) return JS_EXCEPTION;
        s->format = static_cast<int>(temp);
        return JS_UNDEFINED;
    }


    // Constructor for Texture
    static JSValue js_Texture_constructor(JSContext *ctx, JSValueConst new_target, int argc, JSValueConst *argv) {
        
        // Expect either 0 arguments (default constructor) or all fields provided
        if (argc != 0 && argc != 5) {
            return JS_ThrowTypeError(ctx, "Expected either 0 arguments or exactly 5 arguments for Texture constructor");
        }
        
        Texture data = {}; // Initialize with defaults

        // Only populate if the user provides all fields 
        if (argc == 5) {
            {
                int64_t temp;
                if (!JS_ToInt64(ctx, &temp, argv[0])) {
                    data.id = static_cast<unsigned int>(temp); 
                }
            }
            {
                int32_t temp;
                if (!JS_ToInt32(ctx, &temp, argv[1])) {
                    data.width = static_cast<int>(temp); 
                }
            }
            {
                int32_t temp;
                if (!JS_ToInt32(ctx, &temp, argv[2])) {
                    data.height = static_cast<int>(temp); 
                }
            }
            {
                int32_t temp;
                if (!JS_ToInt32(ctx, &temp, argv[3])) {
                    data.mipmaps = static_cast<int>(temp); 
                }
            }
            {
                int32_t temp;
                if (!JS_ToInt32(ctx, &temp, argv[4])) {
                    data.format = static_cast<int>(temp); 
                }
            }
        }

        return JS_NewTexture(ctx, data);
    }

    constexpr JSCFunctionListEntry js_Texture_proto_funcs[] = {
        JS_CGETSET_DEF("id", js_Texture_get_id, js_Texture_set_id),
        JS_CGETSET_DEF("width", js_Texture_get_width, js_Texture_set_width),
        JS_CGETSET_DEF("height", js_Texture_get_height, js_Texture_set_height),
        JS_CGETSET_DEF("mipmaps", js_Texture_get_mipmaps, js_Texture_set_mipmaps),
        JS_CGETSET_DEF("format", js_Texture_get_format, js_Texture_set_format),
    };

    static void InitTextureBinding(JSContext *ctx, JSValue ns) {
        JSRuntime *rt = JS_GetRuntime(ctx);
        if (js_Texture_class_id == 0) {
            JS_NewClassID(rt, &js_Texture_class_id);
        }

        JSClassDef def{ .class_name = "Texture", .finalizer = js_Texture_finalizer };
        JS_NewClass(rt, js_Texture_class_id, &def);

        JSValue proto = JS_NewObject(ctx);
        JS_SetPropertyFunctionList(ctx, proto, js_Texture_proto_funcs, 5);
        JS_SetClassProto(ctx, js_Texture_class_id, proto);

        // Create the constructor function and attach it to the namespace
        JSValue ctor = JS_NewCFunction2(ctx, js_Texture_constructor, "Texture", 5, JS_CFUNC_constructor, 0);
        JS_SetConstructor(ctx, ctor, proto);


        JS_SetPropertyStr(ctx, ns, "Texture", ctor);
    }


    // Alias: Texture2D maps to Texture ---
    JSValue JS_NewTexture2D(JSContext *ctx, Texture data) {
        return JS_NewTexture(ctx, data);
    }


    void InitAllStructs(JSContext *ctx, JSValue ns) {
        InitVector2Binding(ctx, ns);
        InitVector3Binding(ctx, ns);
        InitVector4Binding(ctx, ns);
        InitMatrixBinding(ctx, ns);
        InitColorBinding(ctx, ns);
        InitRectangleBinding(ctx, ns);
        InitImageBinding(ctx, ns);
        InitTextureBinding(ctx, ns);
    }

} // namespace RaylibBindings