// This file is auto-generated by the autobind tool. Do not edit manually.

#include <quickjs.h>
#include <raylib.h>
#include <vector>
#include <memory>
#include "rl_bindings.hpp"

namespace RaylibBindings {

    JSValue JS_InitWindow(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: width (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t width;
        if (JS_ToInt32(ctx, &width, argv[0])) return JS_EXCEPTION;

        // Parameter: height (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t height;
        if (JS_ToInt32(ctx, &height, argv[1])) return JS_EXCEPTION;

        // Parameter: title (Type: const char *)
        const char *title = JS_ToCString(ctx, argv[2]);
        if (!title) return JS_EXCEPTION;


        // Call the Raylib function (no return value)
        InitWindow(width, height, title);

        // Free the C string after the function call
        JS_FreeCString(ctx, title);
        
        // No return value
        return JS_UNDEFINED;
    }

    JSValue JS_CloseWindow(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {


        // Call the Raylib function (no return value)
        CloseWindow();

        
        // No return value
        return JS_UNDEFINED;
    }

    JSValue JS_WindowShouldClose(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {


        // Call the Raylib function and store the result
        const auto result = WindowShouldClose();

        
        // Return a primitive type
        return JS_NewBool(ctx, result);
    }

    JSValue JS_IsWindowReady(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {


        // Call the Raylib function and store the result
        const auto result = IsWindowReady();

        
        // Return a primitive type
        return JS_NewBool(ctx, result);
    }

    JSValue JS_IsWindowFullscreen(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {


        // Call the Raylib function and store the result
        const auto result = IsWindowFullscreen();

        
        // Return a primitive type
        return JS_NewBool(ctx, result);
    }

    JSValue JS_IsWindowHidden(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {


        // Call the Raylib function and store the result
        const auto result = IsWindowHidden();

        
        // Return a primitive type
        return JS_NewBool(ctx, result);
    }

    JSValue JS_IsWindowMinimized(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {


        // Call the Raylib function and store the result
        const auto result = IsWindowMinimized();

        
        // Return a primitive type
        return JS_NewBool(ctx, result);
    }

    JSValue JS_IsWindowMaximized(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {


        // Call the Raylib function and store the result
        const auto result = IsWindowMaximized();

        
        // Return a primitive type
        return JS_NewBool(ctx, result);
    }

    JSValue JS_IsWindowFocused(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {


        // Call the Raylib function and store the result
        const auto result = IsWindowFocused();

        
        // Return a primitive type
        return JS_NewBool(ctx, result);
    }

    JSValue JS_IsWindowResized(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {


        // Call the Raylib function and store the result
        const auto result = IsWindowResized();

        
        // Return a primitive type
        return JS_NewBool(ctx, result);
    }

    JSValue JS_IsWindowState(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: flag (Type: unsigned int)
        // Handle other parameter types by converting from JS to C++
        int64_t flag;
        if (JS_ToInt64(ctx, &flag, argv[0])) return JS_EXCEPTION;


        // Call the Raylib function and store the result
        const auto result = IsWindowState(flag);

        
        // Return a primitive type
        return JS_NewBool(ctx, result);
    }

    JSValue JS_SetWindowState(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: flags (Type: unsigned int)
        // Handle other parameter types by converting from JS to C++
        int64_t flags;
        if (JS_ToInt64(ctx, &flags, argv[0])) return JS_EXCEPTION;


        // Call the Raylib function (no return value)
        SetWindowState(flags);

        
        // No return value
        return JS_UNDEFINED;
    }

    JSValue JS_ClearWindowState(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: flags (Type: unsigned int)
        // Handle other parameter types by converting from JS to C++
        int64_t flags;
        if (JS_ToInt64(ctx, &flags, argv[0])) return JS_EXCEPTION;


        // Call the Raylib function (no return value)
        ClearWindowState(flags);

        
        // No return value
        return JS_UNDEFINED;
    }

    JSValue JS_GetScreenWidth(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {


        // Call the Raylib function and store the result
        const auto result = GetScreenWidth();

        
        // Return a primitive type
        return JS_NewInt32(ctx, result);
    }

    JSValue JS_GetScreenHeight(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {


        // Call the Raylib function and store the result
        const auto result = GetScreenHeight();

        
        // Return a primitive type
        return JS_NewInt32(ctx, result);
    }

    JSValue JS_GetRenderWidth(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {


        // Call the Raylib function and store the result
        const auto result = GetRenderWidth();

        
        // Return a primitive type
        return JS_NewInt32(ctx, result);
    }

    JSValue JS_GetRenderHeight(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {


        // Call the Raylib function and store the result
        const auto result = GetRenderHeight();

        
        // Return a primitive type
        return JS_NewInt32(ctx, result);
    }

    JSValue JS_GetMonitorCount(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {


        // Call the Raylib function and store the result
        const auto result = GetMonitorCount();

        
        // Return a primitive type
        return JS_NewInt32(ctx, result);
    }

    JSValue JS_GetMonitorWidth(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: monitor (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t monitor;
        if (JS_ToInt32(ctx, &monitor, argv[0])) return JS_EXCEPTION;


        // Call the Raylib function and store the result
        const auto result = GetMonitorWidth(monitor);

        
        // Return a primitive type
        return JS_NewInt32(ctx, result);
    }

    JSValue JS_GetMonitorHeight(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: monitor (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t monitor;
        if (JS_ToInt32(ctx, &monitor, argv[0])) return JS_EXCEPTION;


        // Call the Raylib function and store the result
        const auto result = GetMonitorHeight(monitor);

        
        // Return a primitive type
        return JS_NewInt32(ctx, result);
    }

    JSValue JS_GetMonitorPhysicalWidth(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: monitor (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t monitor;
        if (JS_ToInt32(ctx, &monitor, argv[0])) return JS_EXCEPTION;


        // Call the Raylib function and store the result
        const auto result = GetMonitorPhysicalWidth(monitor);

        
        // Return a primitive type
        return JS_NewInt32(ctx, result);
    }

    JSValue JS_GetMonitorPhysicalHeight(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: monitor (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t monitor;
        if (JS_ToInt32(ctx, &monitor, argv[0])) return JS_EXCEPTION;


        // Call the Raylib function and store the result
        const auto result = GetMonitorPhysicalHeight(monitor);

        
        // Return a primitive type
        return JS_NewInt32(ctx, result);
    }

    JSValue JS_GetMonitorRefreshRate(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: monitor (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t monitor;
        if (JS_ToInt32(ctx, &monitor, argv[0])) return JS_EXCEPTION;


        // Call the Raylib function and store the result
        const auto result = GetMonitorRefreshRate(monitor);

        
        // Return a primitive type
        return JS_NewInt32(ctx, result);
    }

    JSValue JS_GetWindowPosition(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {


        // Call the Raylib function and store the struct result
        const auto result = GetWindowPosition();

        
        // Return a struct by wrapping it in a JS object
        return JS_NewVector2(ctx, result);
    }

    JSValue JS_GetWindowScaleDPI(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {


        // Call the Raylib function and store the struct result
        const auto result = GetWindowScaleDPI();

        
        // Return a struct by wrapping it in a JS object
        return JS_NewVector2(ctx, result);
    }

    JSValue JS_ClearBackground(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: color (Type: Color)
        // Handle struct parameters by retrieving the opaque pointer from the JS object
        auto *color_ptr = static_cast<Color*>(JS_GetOpaque2(ctx, argv[0], js_Color_class_id));
        if (!color_ptr) return JS_EXCEPTION;
        // Dereference for non-pointer struct parameters
        Color color = *color_ptr;


        // Call the Raylib function (no return value)
        ClearBackground(color);

        
        // No return value
        return JS_UNDEFINED;
    }

    JSValue JS_BeginDrawing(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {


        // Call the Raylib function (no return value)
        BeginDrawing();

        
        // No return value
        return JS_UNDEFINED;
    }

    JSValue JS_EndDrawing(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {


        // Call the Raylib function (no return value)
        EndDrawing();

        
        // No return value
        return JS_UNDEFINED;
    }

    JSValue JS_SetTargetFPS(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: fps (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t fps;
        if (JS_ToInt32(ctx, &fps, argv[0])) return JS_EXCEPTION;


        // Call the Raylib function (no return value)
        SetTargetFPS(fps);

        
        // No return value
        return JS_UNDEFINED;
    }

    JSValue JS_GetFrameTime(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {


        // Call the Raylib function and store the result
        const auto result = GetFrameTime();

        
        // Return a primitive type
        return JS_NewFloat64(ctx, result);
    }

    JSValue JS_TraceLog(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {



        // Parameter: logLevel (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t logLevel;
        if (JS_ToInt32(ctx, &logLevel, argv[0])) return JS_EXCEPTION;

        TraceLog(LOG_INFO, "logLevel %d", logLevel);

        // Parameter: text (Type: const char *)
        const char *text = JS_ToCString(ctx, argv[1]);
        if (!text) return JS_EXCEPTION;

        // Parameter: args (Type: ...)
        // Handle other parameter types by converting from JS to C++
        int32_t args;
        if (JS_ToInt32(ctx, &args, argv[2])) return JS_EXCEPTION;


        // Call the Raylib function (no return value)
        TraceLog(logLevel, text, args);

        // Free the C string after the function call
        JS_FreeCString(ctx, text);
        
        // No return value
        return JS_UNDEFINED;
    }

    JSValue JS_IsKeyPressed(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: key (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t key;
        if (JS_ToInt32(ctx, &key, argv[0])) return JS_EXCEPTION;


        // Call the Raylib function and store the result
        const auto result = IsKeyPressed(key);

        
        // Return a primitive type
        return JS_NewBool(ctx, result);
    }

    JSValue JS_IsKeyPressedRepeat(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: key (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t key;
        if (JS_ToInt32(ctx, &key, argv[0])) return JS_EXCEPTION;


        // Call the Raylib function and store the result
        const auto result = IsKeyPressedRepeat(key);

        
        // Return a primitive type
        return JS_NewBool(ctx, result);
    }

    JSValue JS_IsKeyDown(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: key (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t key;
        if (JS_ToInt32(ctx, &key, argv[0])) return JS_EXCEPTION;


        // Call the Raylib function and store the result
        const auto result = IsKeyDown(key);

        
        // Return a primitive type
        return JS_NewBool(ctx, result);
    }

    JSValue JS_IsKeyReleased(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: key (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t key;
        if (JS_ToInt32(ctx, &key, argv[0])) return JS_EXCEPTION;


        // Call the Raylib function and store the result
        const auto result = IsKeyReleased(key);

        
        // Return a primitive type
        return JS_NewBool(ctx, result);
    }

    JSValue JS_IsKeyUp(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: key (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t key;
        if (JS_ToInt32(ctx, &key, argv[0])) return JS_EXCEPTION;


        // Call the Raylib function and store the result
        const auto result = IsKeyUp(key);

        
        // Return a primitive type
        return JS_NewBool(ctx, result);
    }

    JSValue JS_GetKeyPressed(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {


        // Call the Raylib function and store the result
        const auto result = GetKeyPressed();

        
        // Return a primitive type
        return JS_NewInt32(ctx, result);
    }

    JSValue JS_SetExitKey(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: key (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t key;
        if (JS_ToInt32(ctx, &key, argv[0])) return JS_EXCEPTION;


        // Call the Raylib function (no return value)
        SetExitKey(key);

        
        // No return value
        return JS_UNDEFINED;
    }

    JSValue JS_IsMouseButtonPressed(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: button (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t button;
        if (JS_ToInt32(ctx, &button, argv[0])) return JS_EXCEPTION;


        // Call the Raylib function and store the result
        const auto result = IsMouseButtonPressed(button);

        
        // Return a primitive type
        return JS_NewBool(ctx, result);
    }

    JSValue JS_IsMouseButtonDown(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: button (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t button;
        if (JS_ToInt32(ctx, &button, argv[0])) return JS_EXCEPTION;


        // Call the Raylib function and store the result
        const auto result = IsMouseButtonDown(button);

        
        // Return a primitive type
        return JS_NewBool(ctx, result);
    }

    JSValue JS_IsMouseButtonReleased(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: button (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t button;
        if (JS_ToInt32(ctx, &button, argv[0])) return JS_EXCEPTION;


        // Call the Raylib function and store the result
        const auto result = IsMouseButtonReleased(button);

        
        // Return a primitive type
        return JS_NewBool(ctx, result);
    }

    JSValue JS_IsMouseButtonUp(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: button (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t button;
        if (JS_ToInt32(ctx, &button, argv[0])) return JS_EXCEPTION;


        // Call the Raylib function and store the result
        const auto result = IsMouseButtonUp(button);

        
        // Return a primitive type
        return JS_NewBool(ctx, result);
    }

    JSValue JS_GetMouseX(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {


        // Call the Raylib function and store the result
        const auto result = GetMouseX();

        
        // Return a primitive type
        return JS_NewInt32(ctx, result);
    }

    JSValue JS_GetMouseY(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {


        // Call the Raylib function and store the result
        const auto result = GetMouseY();

        
        // Return a primitive type
        return JS_NewInt32(ctx, result);
    }

    JSValue JS_GetMousePosition(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {


        // Call the Raylib function and store the struct result
        const auto result = GetMousePosition();

        
        // Return a struct by wrapping it in a JS object
        return JS_NewVector2(ctx, result);
    }

    JSValue JS_SetMousePosition(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: x (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t x;
        if (JS_ToInt32(ctx, &x, argv[0])) return JS_EXCEPTION;

        // Parameter: y (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t y;
        if (JS_ToInt32(ctx, &y, argv[1])) return JS_EXCEPTION;


        // Call the Raylib function (no return value)
        SetMousePosition(x, y);

        
        // No return value
        return JS_UNDEFINED;
    }

    JSValue JS_SetMouseOffset(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: offsetX (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t offsetX;
        if (JS_ToInt32(ctx, &offsetX, argv[0])) return JS_EXCEPTION;

        // Parameter: offsetY (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t offsetY;
        if (JS_ToInt32(ctx, &offsetY, argv[1])) return JS_EXCEPTION;


        // Call the Raylib function (no return value)
        SetMouseOffset(offsetX, offsetY);

        
        // No return value
        return JS_UNDEFINED;
    }

    JSValue JS_SetMouseScale(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: scaleX (Type: float)
        // Handle other parameter types by converting from JS to C++
        double scaleX;
        if (JS_ToFloat64(ctx, &scaleX, argv[0])) return JS_EXCEPTION;

        // Parameter: scaleY (Type: float)
        // Handle other parameter types by converting from JS to C++
        double scaleY;
        if (JS_ToFloat64(ctx, &scaleY, argv[1])) return JS_EXCEPTION;


        // Call the Raylib function (no return value)
        SetMouseScale(scaleX, scaleY);

        
        // No return value
        return JS_UNDEFINED;
    }

    JSValue JS_GetMouseWheelMove(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {


        // Call the Raylib function and store the result
        const auto result = GetMouseWheelMove();

        
        // Return a primitive type
        return JS_NewFloat64(ctx, result);
    }

    JSValue JS_GetMouseWheelMoveV(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {


        // Call the Raylib function and store the struct result
        const auto result = GetMouseWheelMoveV();

        
        // Return a struct by wrapping it in a JS object
        return JS_NewVector2(ctx, result);
    }

    JSValue JS_DrawPixel(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: posX (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t posX;
        if (JS_ToInt32(ctx, &posX, argv[0])) return JS_EXCEPTION;

        // Parameter: posY (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t posY;
        if (JS_ToInt32(ctx, &posY, argv[1])) return JS_EXCEPTION;

        // Parameter: color (Type: Color)
        // Handle struct parameters by retrieving the opaque pointer from the JS object
        auto *color_ptr = static_cast<Color*>(JS_GetOpaque2(ctx, argv[2], js_Color_class_id));
        if (!color_ptr) return JS_EXCEPTION;
        // Dereference for non-pointer struct parameters
        Color color = *color_ptr;


        // Call the Raylib function (no return value)
        DrawPixel(posX, posY, color);

        
        // No return value
        return JS_UNDEFINED;
    }

    JSValue JS_DrawPixelV(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: position (Type: Vector2)
        // Handle struct parameters by retrieving the opaque pointer from the JS object
        auto *position_ptr = static_cast<Vector2*>(JS_GetOpaque2(ctx, argv[0], js_Vector2_class_id));
        if (!position_ptr) return JS_EXCEPTION;
        // Dereference for non-pointer struct parameters
        Vector2 position = *position_ptr;

        // Parameter: color (Type: Color)
        // Handle struct parameters by retrieving the opaque pointer from the JS object
        auto *color_ptr = static_cast<Color*>(JS_GetOpaque2(ctx, argv[1], js_Color_class_id));
        if (!color_ptr) return JS_EXCEPTION;
        // Dereference for non-pointer struct parameters
        Color color = *color_ptr;


        // Call the Raylib function (no return value)
        DrawPixelV(position, color);

        
        // No return value
        return JS_UNDEFINED;
    }

    JSValue JS_DrawLine(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: startPosX (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t startPosX;
        if (JS_ToInt32(ctx, &startPosX, argv[0])) return JS_EXCEPTION;

        // Parameter: startPosY (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t startPosY;
        if (JS_ToInt32(ctx, &startPosY, argv[1])) return JS_EXCEPTION;

        // Parameter: endPosX (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t endPosX;
        if (JS_ToInt32(ctx, &endPosX, argv[2])) return JS_EXCEPTION;

        // Parameter: endPosY (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t endPosY;
        if (JS_ToInt32(ctx, &endPosY, argv[3])) return JS_EXCEPTION;

        // Parameter: color (Type: Color)
        // Handle struct parameters by retrieving the opaque pointer from the JS object
        auto *color_ptr = static_cast<Color*>(JS_GetOpaque2(ctx, argv[4], js_Color_class_id));
        if (!color_ptr) return JS_EXCEPTION;
        // Dereference for non-pointer struct parameters
        Color color = *color_ptr;


        // Call the Raylib function (no return value)
        DrawLine(startPosX, startPosY, endPosX, endPosY, color);

        
        // No return value
        return JS_UNDEFINED;
    }

    JSValue JS_DrawLineV(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: startPos (Type: Vector2)
        // Handle struct parameters by retrieving the opaque pointer from the JS object
        auto *startPos_ptr = static_cast<Vector2*>(JS_GetOpaque2(ctx, argv[0], js_Vector2_class_id));
        if (!startPos_ptr) return JS_EXCEPTION;
        // Dereference for non-pointer struct parameters
        Vector2 startPos = *startPos_ptr;

        // Parameter: endPos (Type: Vector2)
        // Handle struct parameters by retrieving the opaque pointer from the JS object
        auto *endPos_ptr = static_cast<Vector2*>(JS_GetOpaque2(ctx, argv[1], js_Vector2_class_id));
        if (!endPos_ptr) return JS_EXCEPTION;
        // Dereference for non-pointer struct parameters
        Vector2 endPos = *endPos_ptr;

        // Parameter: color (Type: Color)
        // Handle struct parameters by retrieving the opaque pointer from the JS object
        auto *color_ptr = static_cast<Color*>(JS_GetOpaque2(ctx, argv[2], js_Color_class_id));
        if (!color_ptr) return JS_EXCEPTION;
        // Dereference for non-pointer struct parameters
        Color color = *color_ptr;


        // Call the Raylib function (no return value)
        DrawLineV(startPos, endPos, color);

        
        // No return value
        return JS_UNDEFINED;
    }

    JSValue JS_DrawLineEx(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: startPos (Type: Vector2)
        // Handle struct parameters by retrieving the opaque pointer from the JS object
        auto *startPos_ptr = static_cast<Vector2*>(JS_GetOpaque2(ctx, argv[0], js_Vector2_class_id));
        if (!startPos_ptr) return JS_EXCEPTION;
        // Dereference for non-pointer struct parameters
        Vector2 startPos = *startPos_ptr;

        // Parameter: endPos (Type: Vector2)
        // Handle struct parameters by retrieving the opaque pointer from the JS object
        auto *endPos_ptr = static_cast<Vector2*>(JS_GetOpaque2(ctx, argv[1], js_Vector2_class_id));
        if (!endPos_ptr) return JS_EXCEPTION;
        // Dereference for non-pointer struct parameters
        Vector2 endPos = *endPos_ptr;

        // Parameter: thick (Type: float)
        // Handle other parameter types by converting from JS to C++
        double thick;
        if (JS_ToFloat64(ctx, &thick, argv[2])) return JS_EXCEPTION;

        // Parameter: color (Type: Color)
        // Handle struct parameters by retrieving the opaque pointer from the JS object
        auto *color_ptr = static_cast<Color*>(JS_GetOpaque2(ctx, argv[3], js_Color_class_id));
        if (!color_ptr) return JS_EXCEPTION;
        // Dereference for non-pointer struct parameters
        Color color = *color_ptr;


        // Call the Raylib function (no return value)
        DrawLineEx(startPos, endPos, thick, color);

        
        // No return value
        return JS_UNDEFINED;
    }

    JSValue JS_DrawLineStrip(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: points (Type: const Vector2 *)
        // Handle struct parameters by retrieving the opaque pointer from the JS object
        auto *points_ptr = static_cast<Vector2*>(JS_GetOpaque2(ctx, argv[0], js_Vector2_class_id));
        if (!points_ptr) return JS_EXCEPTION;
        // Pass the pointer directly for pointer parameters
        const Vector2 * points = points_ptr;

        // Parameter: pointCount (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t pointCount;
        if (JS_ToInt32(ctx, &pointCount, argv[1])) return JS_EXCEPTION;

        // Parameter: color (Type: Color)
        // Handle struct parameters by retrieving the opaque pointer from the JS object
        auto *color_ptr = static_cast<Color*>(JS_GetOpaque2(ctx, argv[2], js_Color_class_id));
        if (!color_ptr) return JS_EXCEPTION;
        // Dereference for non-pointer struct parameters
        Color color = *color_ptr;


        // Call the Raylib function (no return value)
        DrawLineStrip(points, pointCount, color);

        
        // No return value
        return JS_UNDEFINED;
    }

    JSValue JS_DrawLineBezier(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: startPos (Type: Vector2)
        // Handle struct parameters by retrieving the opaque pointer from the JS object
        auto *startPos_ptr = static_cast<Vector2*>(JS_GetOpaque2(ctx, argv[0], js_Vector2_class_id));
        if (!startPos_ptr) return JS_EXCEPTION;
        // Dereference for non-pointer struct parameters
        Vector2 startPos = *startPos_ptr;

        // Parameter: endPos (Type: Vector2)
        // Handle struct parameters by retrieving the opaque pointer from the JS object
        auto *endPos_ptr = static_cast<Vector2*>(JS_GetOpaque2(ctx, argv[1], js_Vector2_class_id));
        if (!endPos_ptr) return JS_EXCEPTION;
        // Dereference for non-pointer struct parameters
        Vector2 endPos = *endPos_ptr;

        // Parameter: thick (Type: float)
        // Handle other parameter types by converting from JS to C++
        double thick;
        if (JS_ToFloat64(ctx, &thick, argv[2])) return JS_EXCEPTION;

        // Parameter: color (Type: Color)
        // Handle struct parameters by retrieving the opaque pointer from the JS object
        auto *color_ptr = static_cast<Color*>(JS_GetOpaque2(ctx, argv[3], js_Color_class_id));
        if (!color_ptr) return JS_EXCEPTION;
        // Dereference for non-pointer struct parameters
        Color color = *color_ptr;


        // Call the Raylib function (no return value)
        DrawLineBezier(startPos, endPos, thick, color);

        
        // No return value
        return JS_UNDEFINED;
    }

    JSValue JS_DrawCircle(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: centerX (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t centerX;
        if (JS_ToInt32(ctx, &centerX, argv[0])) return JS_EXCEPTION;

        // Parameter: centerY (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t centerY;
        if (JS_ToInt32(ctx, &centerY, argv[1])) return JS_EXCEPTION;

        // Parameter: radius (Type: float)
        // Handle other parameter types by converting from JS to C++
        double radius;
        if (JS_ToFloat64(ctx, &radius, argv[2])) return JS_EXCEPTION;

        // Parameter: color (Type: Color)
        // Handle struct parameters by retrieving the opaque pointer from the JS object
        auto *color_ptr = static_cast<Color*>(JS_GetOpaque2(ctx, argv[3], js_Color_class_id));
        if (!color_ptr) return JS_EXCEPTION;
        // Dereference for non-pointer struct parameters
        Color color = *color_ptr;


        // Call the Raylib function (no return value)
        DrawCircle(centerX, centerY, radius, color);

        
        // No return value
        return JS_UNDEFINED;
    }

    JSValue JS_DrawRectangle(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: posX (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t posX;
        if (JS_ToInt32(ctx, &posX, argv[0])) return JS_EXCEPTION;

        // Parameter: posY (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t posY;
        if (JS_ToInt32(ctx, &posY, argv[1])) return JS_EXCEPTION;

        // Parameter: width (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t width;
        if (JS_ToInt32(ctx, &width, argv[2])) return JS_EXCEPTION;

        // Parameter: height (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t height;
        if (JS_ToInt32(ctx, &height, argv[3])) return JS_EXCEPTION;

        // Parameter: color (Type: Color)
        // Handle struct parameters by retrieving the opaque pointer from the JS object
        auto *color_ptr = static_cast<Color*>(JS_GetOpaque2(ctx, argv[4], js_Color_class_id));
        if (!color_ptr) return JS_EXCEPTION;
        // Dereference for non-pointer struct parameters
        Color color = *color_ptr;


        // Call the Raylib function (no return value)
        DrawRectangle(posX, posY, width, height, color);

        
        // No return value
        return JS_UNDEFINED;
    }

    JSValue JS_LoadTexture(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: fileName (Type: const char *)
        const char *fileName = JS_ToCString(ctx, argv[0]);
        if (!fileName) return JS_EXCEPTION;


        // Call the Raylib function and store the struct result
        const auto result = LoadTexture(fileName);

        // Free the C string after the function call
        JS_FreeCString(ctx, fileName);
        
        // Return a struct by wrapping it in a JS object
        return JS_NewTexture2D(ctx, result);
    }

    JSValue JS_UnloadTexture(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: texture (Type: Texture2D)
        // Handle struct parameters by retrieving the opaque pointer from the JS object
        auto *texture_ptr = static_cast<Texture2D*>(JS_GetOpaque2(ctx, argv[0], js_Texture2D_class_id));
        if (!texture_ptr) return JS_EXCEPTION;
        // Dereference for non-pointer struct parameters
        Texture2D texture = *texture_ptr;


        // Call the Raylib function (no return value)
        UnloadTexture(texture);

        
        // No return value
        return JS_UNDEFINED;
    }

    JSValue JS_DrawTexture(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: texture (Type: Texture2D)
        // Handle struct parameters by retrieving the opaque pointer from the JS object
        auto *texture_ptr = static_cast<Texture2D*>(JS_GetOpaque2(ctx, argv[0], js_Texture2D_class_id));
        if (!texture_ptr) return JS_EXCEPTION;
        // Dereference for non-pointer struct parameters
        Texture2D texture = *texture_ptr;

        // Parameter: posX (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t posX;
        if (JS_ToInt32(ctx, &posX, argv[1])) return JS_EXCEPTION;

        // Parameter: posY (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t posY;
        if (JS_ToInt32(ctx, &posY, argv[2])) return JS_EXCEPTION;

        // Parameter: tint (Type: Color)
        // Handle struct parameters by retrieving the opaque pointer from the JS object
        auto *tint_ptr = static_cast<Color*>(JS_GetOpaque2(ctx, argv[3], js_Color_class_id));
        if (!tint_ptr) return JS_EXCEPTION;
        // Dereference for non-pointer struct parameters
        Color tint = *tint_ptr;


        // Call the Raylib function (no return value)
        DrawTexture(texture, posX, posY, tint);

        
        // No return value
        return JS_UNDEFINED;
    }

    JSValue JS_DrawFPS(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: posX (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t posX;
        if (JS_ToInt32(ctx, &posX, argv[0])) return JS_EXCEPTION;

        // Parameter: posY (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t posY;
        if (JS_ToInt32(ctx, &posY, argv[1])) return JS_EXCEPTION;


        // Call the Raylib function (no return value)
        DrawFPS(posX, posY);

        
        // No return value
        return JS_UNDEFINED;
    }

    JSValue JS_DrawText(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) noexcept {

        // Parameter: text (Type: const char *)
        const char *text = JS_ToCString(ctx, argv[0]);
        if (!text) return JS_EXCEPTION;

        // Parameter: posX (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t posX;
        if (JS_ToInt32(ctx, &posX, argv[1])) return JS_EXCEPTION;

        // Parameter: posY (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t posY;
        if (JS_ToInt32(ctx, &posY, argv[2])) return JS_EXCEPTION;

        // Parameter: fontSize (Type: int)
        // Handle other parameter types by converting from JS to C++
        int32_t fontSize;
        if (JS_ToInt32(ctx, &fontSize, argv[3])) return JS_EXCEPTION;

        // Parameter: color (Type: Color)
        // Handle struct parameters by retrieving the opaque pointer from the JS object
        auto *color_ptr = static_cast<Color*>(JS_GetOpaque2(ctx, argv[4], js_Color_class_id));
        if (!color_ptr) return JS_EXCEPTION;
        // Dereference for non-pointer struct parameters
        Color color = *color_ptr;


        // Call the Raylib function (no return value)
        DrawText(text, posX, posY, fontSize, color);

        // Free the C string after the function call
        JS_FreeCString(ctx, text);
        
        // No return value
        return JS_UNDEFINED;
    }


    static constexpr JSCFunctionListEntry js_raylib_funcs[] = {
        JS_CFUNC_DEF("InitWindow", 3, JS_InitWindow),
        JS_CFUNC_DEF("CloseWindow", 0, JS_CloseWindow),
        JS_CFUNC_DEF("WindowShouldClose", 0, JS_WindowShouldClose),
        JS_CFUNC_DEF("IsWindowReady", 0, JS_IsWindowReady),
        JS_CFUNC_DEF("IsWindowFullscreen", 0, JS_IsWindowFullscreen),
        JS_CFUNC_DEF("IsWindowHidden", 0, JS_IsWindowHidden),
        JS_CFUNC_DEF("IsWindowMinimized", 0, JS_IsWindowMinimized),
        JS_CFUNC_DEF("IsWindowMaximized", 0, JS_IsWindowMaximized),
        JS_CFUNC_DEF("IsWindowFocused", 0, JS_IsWindowFocused),
        JS_CFUNC_DEF("IsWindowResized", 0, JS_IsWindowResized),
        JS_CFUNC_DEF("IsWindowState", 1, JS_IsWindowState),
        JS_CFUNC_DEF("SetWindowState", 1, JS_SetWindowState),
        JS_CFUNC_DEF("ClearWindowState", 1, JS_ClearWindowState),
        JS_CFUNC_DEF("GetScreenWidth", 0, JS_GetScreenWidth),
        JS_CFUNC_DEF("GetScreenHeight", 0, JS_GetScreenHeight),
        JS_CFUNC_DEF("GetRenderWidth", 0, JS_GetRenderWidth),
        JS_CFUNC_DEF("GetRenderHeight", 0, JS_GetRenderHeight),
        JS_CFUNC_DEF("GetMonitorCount", 0, JS_GetMonitorCount),
        JS_CFUNC_DEF("GetMonitorWidth", 1, JS_GetMonitorWidth),
        JS_CFUNC_DEF("GetMonitorHeight", 1, JS_GetMonitorHeight),
        JS_CFUNC_DEF("GetMonitorPhysicalWidth", 1, JS_GetMonitorPhysicalWidth),
        JS_CFUNC_DEF("GetMonitorPhysicalHeight", 1, JS_GetMonitorPhysicalHeight),
        JS_CFUNC_DEF("GetMonitorRefreshRate", 1, JS_GetMonitorRefreshRate),
        JS_CFUNC_DEF("GetWindowPosition", 0, JS_GetWindowPosition),
        JS_CFUNC_DEF("GetWindowScaleDPI", 0, JS_GetWindowScaleDPI),
        JS_CFUNC_DEF("ClearBackground", 1, JS_ClearBackground),
        JS_CFUNC_DEF("BeginDrawing", 0, JS_BeginDrawing),
        JS_CFUNC_DEF("EndDrawing", 0, JS_EndDrawing),
        JS_CFUNC_DEF("SetTargetFPS", 1, JS_SetTargetFPS),
        JS_CFUNC_DEF("GetFrameTime", 0, JS_GetFrameTime),
        JS_CFUNC_DEF("TraceLog", 3, JS_TraceLog),
        JS_CFUNC_DEF("IsKeyPressed", 1, JS_IsKeyPressed),
        JS_CFUNC_DEF("IsKeyPressedRepeat", 1, JS_IsKeyPressedRepeat),
        JS_CFUNC_DEF("IsKeyDown", 1, JS_IsKeyDown),
        JS_CFUNC_DEF("IsKeyReleased", 1, JS_IsKeyReleased),
        JS_CFUNC_DEF("IsKeyUp", 1, JS_IsKeyUp),
        JS_CFUNC_DEF("GetKeyPressed", 0, JS_GetKeyPressed),
        JS_CFUNC_DEF("SetExitKey", 1, JS_SetExitKey),
        JS_CFUNC_DEF("IsMouseButtonPressed", 1, JS_IsMouseButtonPressed),
        JS_CFUNC_DEF("IsMouseButtonDown", 1, JS_IsMouseButtonDown),
        JS_CFUNC_DEF("IsMouseButtonReleased", 1, JS_IsMouseButtonReleased),
        JS_CFUNC_DEF("IsMouseButtonUp", 1, JS_IsMouseButtonUp),
        JS_CFUNC_DEF("GetMouseX", 0, JS_GetMouseX),
        JS_CFUNC_DEF("GetMouseY", 0, JS_GetMouseY),
        JS_CFUNC_DEF("GetMousePosition", 0, JS_GetMousePosition),
        JS_CFUNC_DEF("SetMousePosition", 2, JS_SetMousePosition),
        JS_CFUNC_DEF("SetMouseOffset", 2, JS_SetMouseOffset),
        JS_CFUNC_DEF("SetMouseScale", 2, JS_SetMouseScale),
        JS_CFUNC_DEF("GetMouseWheelMove", 0, JS_GetMouseWheelMove),
        JS_CFUNC_DEF("GetMouseWheelMoveV", 0, JS_GetMouseWheelMoveV),
        JS_CFUNC_DEF("DrawPixel", 3, JS_DrawPixel),
        JS_CFUNC_DEF("DrawPixelV", 2, JS_DrawPixelV),
        JS_CFUNC_DEF("DrawLine", 5, JS_DrawLine),
        JS_CFUNC_DEF("DrawLineV", 3, JS_DrawLineV),
        JS_CFUNC_DEF("DrawLineEx", 4, JS_DrawLineEx),
        JS_CFUNC_DEF("DrawLineStrip", 3, JS_DrawLineStrip),
        JS_CFUNC_DEF("DrawLineBezier", 4, JS_DrawLineBezier),
        JS_CFUNC_DEF("DrawCircle", 4, JS_DrawCircle),
        JS_CFUNC_DEF("DrawRectangle", 5, JS_DrawRectangle),
        JS_CFUNC_DEF("LoadTexture", 1, JS_LoadTexture),
        JS_CFUNC_DEF("UnloadTexture", 1, JS_UnloadTexture),
        JS_CFUNC_DEF("DrawTexture", 4, JS_DrawTexture),
        JS_CFUNC_DEF("DrawFPS", 2, JS_DrawFPS),
        JS_CFUNC_DEF("DrawText", 5, JS_DrawText),
    };

    void InitAllFunctions(JSContext *ctx, JSValue ns) {
        JS_SetPropertyFunctionList(ctx, ns, js_raylib_funcs, 64);
    }

} // namespace RaylibBindings