name: Build
concurrency:
  group: build
  cancel-in-progress: false
on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Installation
        run: sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
      - uses: actions/checkout@v6
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          package-cache: true
          actions-cache-key: ${{ runner.os }}-xmake-${{ hashFiles('xmake.lua') }}
      - name: Build
        run: xmake -y
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          package-cache: true
          actions-cache-key: ${{ runner.os }}-xmake-${{ hashFiles('xmake.lua') }}
      - name: Build
        run: xmake -y