name: Build
concurrency:
  group: build
  cancel-in-progress: true
on:
  pull_request:
    branches:
      - main
      - master
    paths:
      - src
      - xmake.lua
      - .github/workflows/build.yml
  push:
    branches:
      - main
      - master
    paths:
      - src
      - xmake.lua
      - .github/workflows/build.yml
jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Installation
        run: sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: '.xmake-cache'
          actions-cache-key: linux-${{ hashFiles('xmake.lua') }}
      - name: Build
        run: xmake -y
      - name: Upload Linux Binary
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifact
          path: bin/
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: '.xmake-cache'
          actions-cache-key: windows-${{ hashFiles('xmake.lua') }}
      - name: Build
        run: xmake -y
      - name: Upload Windows Binary
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifact
          path: bin/