name: Build
concurrency:
  group: build
  cancel-in-progress: true
on:
  pull_request:
    branches:
      - main
      - master
    paths:
      - src
      - xmake.lua
      - .github/workflows/build.yml
  push:
    branches:
      - main
      - master
    paths:
      - src
      - xmake.lua
      - .github/workflows/build.yml
jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Installation
        run: sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
      - uses: actions/checkout@v6
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: '.xmake-cache'
          actions-cache-key: linux-${{ hashFiles('xmake.lua') }}
      - name: Build
        run: xmake -y
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: '.xmake-cache'
          actions-cache-key: windows-${{ hashFiles('xmake.lua') }}
      - name: Build
        run: xmake -y
  haiku-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build on Haiku
        uses: cross-platform-actions/action@v0.32.0
        with:
          operating_system: haiku
          version: r1beta5
          sync_files: 'true'
          run: |
            # 1. Install dependencies
            # pkgman is non-interactive by default in scripts, 
            # but -y ensures it doesn't hang.
            pkgman install -y xmake raylib_devel
            
            # 2. Build the project
            # We use xmake as requested
            xmake -y